C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/drivers/inc/ADC.h File Reference
ADC Library.
Macros
ADC Reference Selections
All the refereneces that can be selected in ADMUX
#define REFERENCE_AREF 0b00000000
Reference the AREF pin.
#define REFERENCE_AVDD 0b01000000
Internal reference AVDD (1.8V)
#define REFERENCE_1_5V 0b10000000
Internal reference 1.5V.
#define REFERENCE_1_6V 0b11000000
Internal reference 1.6V.
ADC Input Channel Selections
Single ended channel options
#define ADC0 0b00000000
ADC0 Pin.
#define ADC1 0b00000001
ADC1 Pin.
#define ADC2 0b00000010
ADC2 Pin.
#define ADC3 0b00000011
ADC3 Pin.
#define ADC4 0b00000100
ADC4 Pin.
#define ADC5 0b00000101
ADC5 Pin.
#define ADC6 0b00000110
ADC6 Pin.
#define ADC7 0b00000111
ADC7 Pin.
#define ADC_VBG 0b00011110
1.2V internal bus(Vbg)
#define ADC_GND 0b00011111
Analog ground (AVSS)
#define ADC_EVDD 0b00100110
Internal digital power (EVDD)
#define ADC_TEMP 0b00101001
Internal temperature sensor.
#define ADC_VDRTBBP 0b00110100
Positive SRAM back-bias.
#define ADC_VDRTBBN 0b00111101
Negative SRAM back-bias.
Functions
void ADC_Init (void)
Initializes the ADC.
void ADC_Reference (unsigned char ref)
int ADC_Convert (unsigned char channel)
float ADC_DieTemp (void)
Detailed Description
ADC Library. Created: 4/10/2015 00:19:53 Author: Camden Miller
Macro Definition Documentation
#define ADC0 0b00000000
ADC0 Pin.
#define ADC1 0b00000001
ADC1 Pin.
Referenced by TGS2600_GetResistance().
#define ADC2 0b00000010
ADC2 Pin.
#define ADC3 0b00000011
ADC3 Pin.
#define ADC4 0b00000100
ADC4 Pin.
#define ADC5 0b00000101
ADC5 Pin.
#define ADC6 0b00000110
ADC6 Pin.
#define ADC7 0b00000111
ADC7 Pin.
#define ADC_EVDD 0b00100110
Internal digital power (EVDD)
#define ADC_GND 0b00011111
Analog ground (AVSS)
#define ADC_TEMP 0b00101001
Internal temperature sensor.
#define ADC_VBG 0b00011110
1.2V internal bus(Vbg)
#define ADC_VDRTBBN 0b00111101
Negative SRAM back-bias.
#define ADC_VDRTBBP 0b00110100
Positive SRAM back-bias.
#define REFERENCE_1_5V 0b10000000
Internal reference 1.5V.
#define REFERENCE_1_6V 0b11000000
Internal reference 1.6V.
#define REFERENCE_AREF 0b00000000
Reference the AREF pin.
Referenced by TGS2600_GetResistance().
#define REFERENCE_AVDD 0b01000000
Internal reference AVDD (1.8V)
Function Documentation
int ADC_Convert (unsigned char channel)
Referenced by TGS2600_GetResistance().
float ADC_DieTemp (void)
void ADC_Init (void)
Initializes the ADC.
Referenced by APP_Init().
void ADC_Reference (unsigned char ref)
Referenced by TGS2600_GetResistance().