C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/drivers/src/ADC.c File Reference
ADC library implementation.
#include <avr/io.h>
*
#include <stdbool.h>
*
#include `drivers/inc/ADC.h`
*
Functions
void ADC_Init (void)
Initializes the ADC.
void ADC_Reference (unsigned char ref)
int ADC_Convert (unsigned char channel)
float ADC_DieTemp (void)
Detailed Description
ADC library implementation. Author: Tony Zhang Camden Miller
Function Documentation
int ADC_Convert (unsigned char channel)
Referenced by TGS2600_GetResistance().
float ADC_DieTemp (void)
void ADC_Init (void)
Initializes the ADC.
Referenced by APP_Init().
void ADC_Reference (unsigned char ref)
Referenced by TGS2600_GetResistance().