C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/ATMOS.c File Reference
The entry function.
#include `utilities/inc/config.h`
*
#include `utilities/inc/common.h`
*
#include `hal.h`
*
#include `phy.h`
*
#include `sys.h`
*
#include `nwk.h`
*
#include `drivers/inc/usart0.h`
*
#include `drivers/inc/TWI.h`
*
#include `drivers/inc/PWR.h`
*
#include `drivers/inc/ADC.h`
*
#include `drivers/inc/SPI.h`
*
#include `drivers/inc/int_timer.h`
*
#include `scheduler/inc/scheduler.h`
*
#include `wrapper/sensor/inc/My_Sensor.h`
*
#include `wrapper/sensor/inc/Si7020_Sensor.h`
*
#include `wrapper/sensor/inc/Temperature_ADC_Sensor.h`
*
#include `wrapper/sensor/inc/BMP280_Sensor.h`
*
#include `avr/io.h`
*
#include `avr/interrupt.h`
*
Functions
static void APP_Init (void)
int main (void)
Detailed Description
The entry function.
Function Documentation
static void APP_Init (void) [static]
References ADC_Init(), BMP280_Init(), BMP280_SetOversampling(), PWR_Init(), PWR_TurnOn5V(), SPI_SlaveInit(), TWI_Init(), and USART0_Init().
Referenced by main().
int main (void)
References APP_Init(), BMP280_FctnInit(), get_next_interval(), init_Event_Timer(), init_set_timer(), init_timeoutq(), load_new_sensor(), New_BMP280_Sensor(), and SYS_Init().