C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/wrapper/sensor/src/BMP280_Sensor.c File Reference
Implementation of BMP280_Sensor struct, which derived from BaseSensor.
#include `wrapper/sensor/inc/BMP280_Sensor.h`
*
#include `devices/inc/BMP280.h`
*
#include <stdio.h>
*
#include <stdlib.h>
*
Functions
void BMP280_FctnInit (BMP280Sensor *this)
int BMP280_Configure (BMP280Sensor *this)
int BMP280_Request (BMP280Sensor *this)
int BMP280_Collect (BMP280Sensor *this)
int BMP280_Error (BMP280Sensor *this)
void BMP280_VTinit (BMP280Sensor *this)
int BMP280_init (BMP280Sensor *this)
int BMP280_reset (BMP280Sensor *this)
int BMP280_getType (BMP280Sensor *this)
BMP280Sensor * New_BMP280_Sensor (int num)
Variables
BMP280_FctnTable BMP280_vmt
BMP280_Abstract_FctnTable BMP280_abstract_vmt
Detailed Description
Implementation of BMP280_Sensor struct, which derived from BaseSensor. Created: 2016/4/6 17:43:53 Author: Anxin Bai
Function Documentation
int BMP280_Collect (BMP280Sensor * this)
References BMP280_GetTemperatureAndPressure().
int BMP280_Configure (BMP280Sensor * this)
int BMP280_Error (BMP280Sensor * this)
void BMP280_FctnInit (BMP280Sensor * this)
References BMP280_vmt.
Referenced by main(), and New_BMP280_Sensor().
int BMP280_getType (BMP280Sensor * this)
References TYPE_SENSOR.
int BMP280_init (BMP280Sensor * this)
int BMP280_Request (BMP280Sensor * this)
References BMP280_StartMeasurment().
int BMP280_reset (BMP280Sensor * this)
void BMP280_VTinit (BMP280Sensor * this)
References BMP280_abstract_vmt.
Referenced by New_BMP280_Sensor().
BMP280Sensor* New_BMP280_Sensor (int num)
References BMP280_FctnInit(), BMP280_VTinit(), _BMP280_Sensor::inherited, and _Base_Sensor::test_num.
Referenced by main().
Variable Documentation
BMP280_Abstract_FctnTable BMP280_abstract_vmt
Initial value:
 {
    BMP280_VTinit,
    BMP280_init,
    BMP280_reset,
    BMP280_getType
}
Referenced by BMP280_VTinit().
BMP280_FctnTable BMP280_vmt
Initial value:
 {
    BMP280_FctnInit,
    BMP280_Configure,
    BMP280_Request,
    BMP280_Collect,
    BMP280_Error
}
Referenced by BMP280_FctnInit().