C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/wrapper/sensor/inc/BMP280_Sensor.h File Reference
Declaration of BMP280_Sensor struct, which derived from BaseSensor.
#include `wrapper/base-class/inc/Base_Sensor.h`
*
Data Structures
struct _BMP280_vmt
struct _BMP280_Abstract_vmt
struct _BMP280_Sensor
Typedefs
typedef struct _BMP280_Sensor BMP280Sensor
typedef struct _BMP280_vmt BMP280_FctnTable
typedef struct _BMP280_Abstract_vmt BMP280_Abstract_FctnTable
Functions
void BMP280_FctnInit (BMP280Sensor *this)
int BMP280_Configure (BMP280Sensor *this)
int BMP280_Request (BMP280Sensor *this)
int BMP280_Collect (BMP280Sensor *this)
int BMP280_Error (BMP280Sensor *this)
void BMP280_VTinit (BMP280Sensor *)
int BMP280_init (BMP280Sensor *)
int BMP280_reset (BMP280Sensor *)
int BMP280_getType (BMP280Sensor *)
BMP280Sensor * New_BMP280_Sensor (int num)
Detailed Description
Declaration of BMP280_Sensor struct, which derived from BaseSensor. Created: 2016/4/6 17:40:39 Author: Anxin Bai
Typedef Documentation
typedef struct _BMP280_Abstract_vmt BMP280_Abstract_FctnTable
typedef struct _BMP280_vmt BMP280_FctnTable
typedef struct _BMP280_Sensor BMP280Sensor
Function Documentation
int BMP280_Collect (BMP280Sensor * this)
References BMP280_GetTemperatureAndPressure().
int BMP280_Configure (BMP280Sensor * this)
int BMP280_Error (BMP280Sensor * this)
void BMP280_FctnInit (BMP280Sensor * this)
References BMP280_vmt.
Referenced by main(), and New_BMP280_Sensor().
int BMP280_getType (BMP280Sensor *)
References TYPE_SENSOR.
int BMP280_init (BMP280Sensor *)
int BMP280_Request (BMP280Sensor * this)
References BMP280_StartMeasurment().
int BMP280_reset (BMP280Sensor *)
void BMP280_VTinit (BMP280Sensor *)
References BMP280_abstract_vmt.
Referenced by New_BMP280_Sensor().
BMP280Sensor* New_BMP280_Sensor (int num)
References BMP280_FctnInit(), BMP280_VTinit(), _BMP280_Sensor::inherited, and _Base_Sensor::test_num.
Referenced by main().