C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/inc/BMP280.h File Reference
BMP280 Interface Library.
#include <stdbool.h>
*
Macros
#define BMP280_ADDR 0x76
Device address.
TWI Status Codes
All the codes that could be given via TWSR
#define BMP280_REG_CONTROL 0xF4
#define BMP280_REG_RESULT_PRESSURE 0xF7
0xF7(msb) , 0xF8(lsb) , 0xF9(xlsb) : stores the pressure data.
#define BMP280_REG_RESULT_TEMPRERATURE 0xFA
0xFA(msb) , 0xFB(lsb) , 0xFC(xlsb) : stores the temperature data.
Command Macros
Measurement commands to issue to BMP280_REG_CONTROL
#define BMP280_COMMAND_TEMPERATURE 0x2E
#define BMP280_COMMAND_PRESSURE0 0x25
#define BMP280_COMMAND_PRESSURE1 0x29
#define BMP280_COMMAND_PRESSURE2 0x2D
#define BMP280_COMMAND_PRESSURE3 0x31
#define BMP280_COMMAND_PRESSURE4 0x5D
Functions
char BMP280_Init (void)
Initializes the BMP280 and reads the calibration data from the device.
char BMP280_GetUnPT (double *, double *)
Gets the uncalibrated temperature and pressure data.
short BMP280_GetOversampling (void)
Gets the oversampling setting for the library.
char BMP280_SetOversampling (short oss)
Sets the oversampling setting for the library.
char BMP280_StartMeasurment (void)
Starts a measurement.
char BMP280_GetTemperatureAndPressure (double *, double *)
Gets temperature and pressure.
char BMP280_CalcTemperature (double *, double *)
Calculates temperature.
char BMP280_CalcPressure (double *, double *)
Calculates pressure.
double BMP280_Sealevel (double, double)
Calculates pressure at sea level given an altitude.
double BMP280_Altitude (double, double)
Calculates altitude.
char BMP280_GetError (void)
Returns the internal library error value.
Detailed Description
BMP280 Interface Library. Created: 2/10/2015 20:25:27 Author: Camden Miller
Macro Definition Documentation
#define BMP280_ADDR 0x76
Device address.
Referenced by BMP280_ReadBytes(), and BMP280_WriteBytes().
#define BMP280_COMMAND_PRESSURE0 0x25
Referenced by BMP280_StartMeasurment().
#define BMP280_COMMAND_PRESSURE1 0x29
Referenced by BMP280_StartMeasurment().
#define BMP280_COMMAND_PRESSURE2 0x2D
Referenced by BMP280_StartMeasurment().
#define BMP280_COMMAND_PRESSURE3 0x31
Referenced by BMP280_StartMeasurment().
#define BMP280_COMMAND_PRESSURE4 0x5D
Referenced by BMP280_StartMeasurment().
#define BMP280_COMMAND_TEMPERATURE 0x2E
#define BMP280_REG_CONTROL 0xF4
Referenced by BMP280_StartMeasurment().
#define BMP280_REG_RESULT_PRESSURE 0xF7
0xF7(msb) , 0xF8(lsb) , 0xF9(xlsb) : stores the pressure data.
Referenced by BMP280_GetUnPT().
#define BMP280_REG_RESULT_TEMPRERATURE 0xFA
0xFA(msb) , 0xFB(lsb) , 0xFC(xlsb) : stores the temperature data.
Function Documentation
double BMP280_Altitude (double P, double P0)
Calculates altitude.
Parameters
in pressure reading
in sea level pressure
Returns
the corrected reading
char BMP280_CalcPressure (double * P, double * uP)
Calculates pressure.
Parameters
out pointer to a place to store the pressure data
in pointer to the uncalibrated pressure data
Returns
status
References dig_P1, dig_P2, dig_P3, dig_P4, dig_P5, dig_P6, dig_P7, dig_P8, dig_P9, and t_fine.
Referenced by BMP280_GetTemperatureAndPressure().
char BMP280_CalcTemperature (double * T, double * uT)
Calculates temperature.
Parameters
out pointer to a place to store the temperature data
in pointer to the uncalibrated temperature data
Returns
status
References dig_T1, dig_T2, dig_T3, and t_fine.
Referenced by BMP280_GetTemperatureAndPressure().
char BMP280_GetError (void)
Returns the internal library error value.
Parameters
in pressure reading
in sea level pressure
Returns
error value
References error.
short BMP280_GetOversampling (void)
Gets the oversampling setting for the library.
Returns
oversampling
References oversampling.
char BMP280_GetTemperatureAndPressure (double * T, double * P)
Gets temperature and pressure.
Parameters
out pointer to a place to store the pressure data
out pointer to a place to store the temperature data
Returns
status
References BMP280_CalcPressure(), BMP280_CalcTemperature(), BMP280_GetUnPT(), and error.
Referenced by BMP280_Collect().
char BMP280_GetUnPT (double * uP, double * uT)
Gets the uncalibrated temperature and pressure data.
Parameters
out pointer to a place to store the pressure data
out pointer to a place to store the temperature data
Returns
status
References BMP280_ReadBytes(), and BMP280_REG_RESULT_PRESSURE.
Referenced by BMP280_GetTemperatureAndPressure().
char BMP280_Init (void)
Initializes the BMP280 and reads the calibration data from the device.
Returns
status (zero on failure, nonzero otherwise)
References BMP280_ReadInt(), BMP280_ReadUInt(), dig_P1, dig_P2, dig_P3, dig_P4, dig_P5, dig_P6, dig_P7, dig_P8, dig_P9, dig_T1, dig_T2, and dig_T3.
Referenced by APP_Init().
double BMP280_Sealevel (double P, double A)
Calculates pressure at sea level given an altitude.
Parameters
in pressure reading
in altitude
Returns
the corrected reading
char BMP280_SetOversampling (short oss)
Sets the oversampling setting for the library.
Parameters
in oss Oversampling setting
Returns
1
References oversampling.
Referenced by APP_Init().
char BMP280_StartMeasurment (void)
Starts a measurement.
Returns
time to wait for result (in ms)
References BMP280_COMMAND_PRESSURE0, BMP280_COMMAND_PRESSURE1, BMP280_COMMAND_PRESSURE2, BMP280_COMMAND_PRESSURE3, BMP280_COMMAND_PRESSURE4, BMP280_REG_CONTROL, BMP280_WriteBytes(), delay, oversampling, and oversampling_t.
Referenced by BMP280_Request().