C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/src/BMP280.c File Reference
BMP280 Pressure Sensor Library implementation.
#include `devices/inc/BMP280.h`
*
#include `drivers/inc/TWI.h`
*
#include `drivers/inc/usart0.h`
*
#include `math.h`
*
Functions
static char BMP280_ReadInt (char address, int *val)
Reads an int from the BMP280.
static char BMP280_ReadUInt (char address, unsigned int *val)
Reads an unsigned int from the BMP280.
static char BMP280_ReadBytes (unsigned char *values, char length)
Reads some bytes from the BMP280.
static char BMP280_WriteBytes (unsigned char *values, char length)
Reads some bytes from the BMP280.
char BMP280_Init (void)
Initializes the BMP280 and reads the calibration data from the device.
short BMP280_GetOversampling (void)
Gets the oversampling setting for the library.
char BMP280_SetOversampling (short oss)
Sets the oversampling setting for the library.
char BMP280_StartMeasurment (void)
Starts a measurement.
char BMP280_GetUnPT (double *uP, double *uT)
Gets the uncalibrated temperature and pressure data.
char BMP280_GetTemperatureAndPressure (double *T, double *P)
Gets temperature and pressure.
char BMP280_CalcTemperature (double *T, double *uT)
Calculates temperature.
char BMP280_CalcPressure (double *P, double *uP)
Calculates pressure.
double BMP280_Sealevel (double P, double A)
Calculates pressure at sea level given an altitude.
double BMP280_Altitude (double P, double P0)
Calculates altitude.
char BMP280_GetError (void)
Returns the internal library error value.
Variables
static int dig_T2
static int dig_T3
static int dig_P2
static int dig_P3
static int dig_P4
static int dig_P5
static int dig_P6
static int dig_P7
static int dig_P8
static int dig_P9
Calibration values from the BMP280.
static unsigned int dig_P1
static unsigned int dig_T1
Calibration values from the BMP280.
static short oversampling
static short oversampling_t
Oversampling sertings.
static long signed int t_fine
static char error
static char status
Detailed Description
BMP280 Pressure Sensor Library implementation. This library is intended only to work on the REV1 base station, check BMP280.h for address defines and the like
Created: 2/10/2015 20:24:55 Author: Camden Miller
Function Documentation
double BMP280_Altitude (double P, double P0)
Calculates altitude.
Parameters
in pressure reading
in sea level pressure
Returns
the corrected reading
char BMP280_CalcPressure (double * P, double * uP)
Calculates pressure.
Parameters
out pointer to a place to store the pressure data
in pointer to the uncalibrated pressure data
Returns
status
References dig_P1, dig_P2, dig_P3, dig_P4, dig_P5, dig_P6, dig_P7, dig_P8, dig_P9, and t_fine.
Referenced by BMP280_GetTemperatureAndPressure().
char BMP280_CalcTemperature (double * T, double * uT)
Calculates temperature.
Parameters
out pointer to a place to store the temperature data
in pointer to the uncalibrated temperature data
Returns
status
References dig_T1, dig_T2, dig_T3, and t_fine.
Referenced by BMP280_GetTemperatureAndPressure().
char BMP280_GetError (void)
Returns the internal library error value.
Parameters
in pressure reading
in sea level pressure
Returns
error value
References error.
short BMP280_GetOversampling (void)
Gets the oversampling setting for the library.
Returns
oversampling
References oversampling.
char BMP280_GetTemperatureAndPressure (double * T, double * P)
Gets temperature and pressure.
Parameters
out pointer to a place to store the pressure data
out pointer to a place to store the temperature data
Returns
status
References BMP280_CalcPressure(), BMP280_CalcTemperature(), BMP280_GetUnPT(), and error.
Referenced by BMP280_Collect().
char BMP280_GetUnPT (double * uP, double * uT)
Gets the uncalibrated temperature and pressure data.
Parameters
out pointer to a place to store the pressure data
out pointer to a place to store the temperature data
Returns
status
References BMP280_ReadBytes(), and BMP280_REG_RESULT_PRESSURE.
Referenced by BMP280_GetTemperatureAndPressure().
char BMP280_Init (void)
Initializes the BMP280 and reads the calibration data from the device.
Returns
status (zero on failure, nonzero otherwise)
References BMP280_ReadInt(), BMP280_ReadUInt(), dig_P1, dig_P2, dig_P3, dig_P4, dig_P5, dig_P6, dig_P7, dig_P8, dig_P9, dig_T1, dig_T2, and dig_T3.
Referenced by APP_Init().
static char BMP280_ReadBytes (unsigned char * values, char length) [static]
Reads some bytes from the BMP280.
Has no buffer overrun protection
Parameters
in *values pointer to an array to store the bytes, put the starting register in values[0]
in length how many bytes to read
Returns
status (zero on failure, nonzero otherwise)
References BMP280_ADDR, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_NACK, TWI_SLAR_ACK, TWI_Stop(), TWI_WriteByte(), and TWSR_MASK.
Referenced by BMP280_GetUnPT(), BMP280_ReadInt(), and BMP280_ReadUInt().
static char BMP280_ReadInt (char address, int * val) [static]
Reads an int from the BMP280.
Parameters
in address The register address of the first byte of the uint
out val* A pointer to a uint to store the received data to
Returns
status (zero on failure, nonzero otherwise)
References BMP280_ReadBytes().
Referenced by BMP280_Init().
static char BMP280_ReadUInt (char address, unsigned int * val) [static]
Reads an unsigned int from the BMP280.
Parameters
in address The register address of the first byte of the uint
out val* A pointer to a uint to store the received data to
Returns
status (zero on failure, nonzero otherwise)
References BMP280_ReadBytes().
Referenced by BMP280_Init().
double BMP280_Sealevel (double P, double A)
Calculates pressure at sea level given an altitude.
Parameters
in pressure reading
in altitude
Returns
the corrected reading
char BMP280_SetOversampling (short oss)
Sets the oversampling setting for the library.
Parameters
in oss Oversampling setting
Returns
1
References oversampling.
Referenced by APP_Init().
char BMP280_StartMeasurment (void)
Starts a measurement.
Returns
time to wait for result (in ms)
References BMP280_COMMAND_PRESSURE0, BMP280_COMMAND_PRESSURE1, BMP280_COMMAND_PRESSURE2, BMP280_COMMAND_PRESSURE3, BMP280_COMMAND_PRESSURE4, BMP280_REG_CONTROL, BMP280_WriteBytes(), delay, oversampling, and oversampling_t.
Referenced by BMP280_Request().
static char BMP280_WriteBytes (unsigned char * values, char length) [static]
Reads some bytes from the BMP280.
Has no buffer overrun protection
Parameters
in *values pointer to an array to send, put the starting register in values[0]
in length how many bytes to write (including the starting register ie. sizeof(values))
Returns
status (zero on failure, nonzero otherwise)
References BMP280_ADDR, TWI_BeginWrite(), TWI_SENT_ACK, TWI_Stop(), and TWI_Write().
Referenced by BMP280_StartMeasurment().
Variable Documentation
unsigned int dig_P1 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P2 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P3 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P4 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P5 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P6 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P7 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P8 [static]
Referenced by BMP280_CalcPressure(), and BMP280_Init().
int dig_P9 [static]
Calibration values from the BMP280.
Referenced by BMP280_CalcPressure(), and BMP280_Init().
unsigned int dig_T1 [static]
Calibration values from the BMP280.
Referenced by BMP280_CalcTemperature(), and BMP280_Init().
int dig_T2 [static]
Referenced by BMP280_CalcTemperature(), and BMP280_Init().
int dig_T3 [static]
Referenced by BMP280_CalcTemperature(), and BMP280_Init().
char error [static]
Referenced by BMP280_GetError(), and BMP280_GetTemperatureAndPressure().
short oversampling [static]
Referenced by BMP280_GetOversampling(), BMP280_SetOversampling(), and BMP280_StartMeasurment().
short oversampling_t [static]
Oversampling sertings.
Referenced by BMP280_StartMeasurment().
char status [static]
Referenced by BMP280_ReadBytes(), K30_readCO2(), nwkTxConfirm(), Si7020_readHumidity(), Si7020_readTemperature(), TWI_Read(), and TWI_Write().
long signed int t_fine [static]
Referenced by BMP280_CalcPressure(), and BMP280_CalcTemperature().