C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/wrapper/base-class/src/Base_Sensor.c File Reference
Implementation of BaseSensor struct, which derived from BaseDevice.
#include `wrapper/base-class/inc/Base_Sensor.h`
*
#include <stdlib.h>
*
#include <stdio.h>
*
Functions
void Base_FctnInit (BaseSensor *this)
int Base_Configure (BaseSensor *this)
int Base_Request (BaseSensor *this)
int Base_Collect (BaseSensor *this)
int Base_Error (BaseSensor *this)
BaseSensor * New_Base_Sensor (int num)
void Base_VTinit (BaseSensor *this)
int Base_Init (BaseSensor *this)
int Base_Reset (BaseSensor *this)
int Base_getType (BaseSensor *this)
Variables
Base_FctnTable Base_vmt
Abstract_FctnTable Abstract_vmt
Detailed Description
Implementation of BaseSensor struct, which derived from BaseDevice. Author: Anxin Bai
Function Documentation
int Base_Collect (BaseSensor * this)
int Base_Configure (BaseSensor * this)
int Base_Error (BaseSensor * this)
void Base_FctnInit (BaseSensor * this)
References Base_vmt.
Referenced by New_Base_Sensor().
int Base_getType (BaseSensor * this)
References TYPE_BASE_SENSOR.
int Base_Init (BaseSensor * this)
int Base_Request (BaseSensor * this)
int Base_Reset (BaseSensor * this)
void Base_VTinit (BaseSensor * this)
References Abstract_vmt.
Referenced by New_Base_Sensor().
BaseSensor* New_Base_Sensor (int num)
References Base_FctnInit(), Base_VTinit(), and _Base_Sensor::test_num.
Variable Documentation
Abstract_FctnTable Abstract_vmt
Initial value:
 {
        Base_VTinit,
        Base_init,
        Base_reset,
        Base_getType
}
Referenced by Base_VTinit().
Base_FctnTable Base_vmt
Initial value:
 {
        Base_FctnInit,
        Base_Configure,
        Base_Request,
        Base_Collect,
        Base_Error
}
Referenced by Base_FctnInit().