C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/wrapper/base-class/inc/Base_Sensor.h File Reference
Declaration of BaseSensor struct, which derived from BaseDevice.
#include `wrapper/base-class/inc/Base_Device.h`
*
Data Structures
struct _Base_vmt
struct _Abstract_vmt
struct _Base_Sensor
Typedefs
typedef struct _Base_Sensor BaseSensor
typedef struct _Base_vmt Base_FctnTable
typedef struct _Abstract_vmt Abstract_FctnTable
Functions
void Base_FctnInit (BaseSensor *this)
int Base_Configure (BaseSensor *this)
int Base_Request (BaseSensor *this)
int Base_Collect (BaseSensor *this)
int Base_Error (BaseSensor *this)
void Base_VTinit (BaseSensor *)
int Base_init (BaseSensor *)
int Base_reset (BaseSensor *)
int Base_getType (BaseSensor *)
BaseSensor * New_Base_Sensor (int num)
Detailed Description
Declaration of BaseSensor struct, which derived from BaseDevice. Author: Anxin Bai
Typedef Documentation
typedef struct _Abstract_vmt Abstract_FctnTable
typedef struct _Base_vmt Base_FctnTable
typedef struct _Base_Sensor BaseSensor
Function Documentation
int Base_Collect (BaseSensor * this)
int Base_Configure (BaseSensor * this)
int Base_Error (BaseSensor * this)
void Base_FctnInit (BaseSensor * this)
References Base_vmt.
Referenced by New_Base_Sensor().
int Base_getType (BaseSensor *)
References TYPE_BASE_SENSOR.
int Base_init (BaseSensor *)
int Base_Request (BaseSensor * this)
int Base_reset (BaseSensor *)
void Base_VTinit (BaseSensor *)
References Abstract_vmt.
Referenced by New_Base_Sensor().
BaseSensor* New_Base_Sensor (int num)
References Base_FctnInit(), Base_VTinit(), and _Base_Sensor::test_num.