C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/src/K30.c File Reference
#include `devices/inc/K30.h`
*
#include `drivers/inc/TWI.h`
*
#include <util/delay.h>
*
#include `drivers/inc/usart0.h`
*
#include <math.h>
*
Functions
int K30_readCO2 ()
Initializes the K30.
Variables
unsigned char readcmd [4] = {0x22,0x00,0x08,0x2A}
Detailed Description
Created: 04/02/2015 18:01:55 Author: Hui Shi
Function Documentation
int K30_readCO2 ()
Initializes the K30.
Returns
status zero
References buffer, readcmd, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_ACK, TWI_SENT_ACK, TWI_SLAR_ACK, TWI_SLAW_ACK, TWI_Stop(), and TWI_Write().
Variable Documentation
unsigned char readcmd[4] = {0x22,0x00,0x08,0x2A}
Referenced by K30_readCO2().