C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/inc/K30.h File Reference
K30 Interface Library.
#include <stdint.h>
*
Macros
#define K30_ADDR 0x68
#define K30_I2_RAM_ADDR 0x20
#define K30_I2_EEPROM_ADDR 0x00
#define SHIFTED_DIVISOR 0x988000
#define K30_WRITE 0xD0
#define K30_READ_RAM 0x22
#define K30_RAM_HI_BYTE 0x08
#define K30_RAM_LO_BYTE 0x09
Functions
int K30_readCO2 ()
Initializes the K30.
Detailed Description
K30 Interface Library. Created: 04/02/2015 18:04:55 Author: Hui Shi
Macro Definition Documentation
#define K30_ADDR 0x68
#define K30_I2_EEPROM_ADDR 0x00
#define K30_I2_RAM_ADDR 0x20
#define K30_RAM_HI_BYTE 0x08
#define K30_RAM_LO_BYTE 0x09
#define K30_READ_RAM 0x22
#define K30_WRITE 0xD0
Status Codes
#define SHIFTED_DIVISOR 0x988000
Referenced by check_crc().
Function Documentation
int K30_readCO2 ()
Initializes the K30.
Returns
status zero
References buffer, readcmd, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_ACK, TWI_SENT_ACK, TWI_SLAR_ACK, TWI_SLAW_ACK, TWI_Stop(), and TWI_Write().