C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/wrapper/sensor/src/My_Sensor.c File Reference
Implementation of My_Sensor struct, which derived from BaseSensor.
#include `wrapper/sensor/inc/My_Sensor.h`
*
#include <stdlib.h>
*
#include <stdio.h>
*
Functions
void My_FctnInit (MySensor *this)
int My_Configure (MySensor *this)
int My_Request (MySensor *this)
int My_Collect (MySensor *this)
int My_Error (MySensor *this)
void My_VTinit (MySensor *this)
int My_init (MySensor *this)
int My_reset (MySensor *this)
int My_getType (MySensor *this)
MySensor * New_My_Sensor (int num)
Variables
My_FctnTable My_vmt
My_Abstract_FctnTable My_abstract_vmt
Detailed Description
Implementation of My_Sensor struct, which derived from BaseSensor. Author: Anxin Bai
Function Documentation
int My_Collect (MySensor * this)
int My_Configure (MySensor * this)
int My_Error (MySensor * this)
void My_FctnInit (MySensor * this)
References My_vmt.
Referenced by New_My_Sensor().
int My_getType (MySensor * this)
References TYPE_SENSOR.
int My_init (MySensor * this)
int My_Request (MySensor * this)
int My_reset (MySensor * this)
void My_VTinit (MySensor * this)
References My_abstract_vmt.
Referenced by New_My_Sensor().
MySensor* New_My_Sensor (int num)
References _My_Sensor::inherited, My_FctnInit(), My_VTinit(), and _Base_Sensor::test_num.
Variable Documentation
My_Abstract_FctnTable My_abstract_vmt
Initial value:
 {
        My_VTinit,
        My_init,
        My_reset,
        My_getType
}
Referenced by My_VTinit().
My_FctnTable My_vmt
Initial value:
 {
        My_FctnInit,
        My_Configure,
        My_Request,
        My_Collect,
        My_Error
}
Referenced by My_FctnInit().