C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/wrapper/sensor/inc/My_Sensor.h File Reference
Declaration of My_Sensor struct, which derived from BaseSensor.
#include `wrapper/base-class/inc/Base_Sensor.h`
*
Data Structures
struct _My_vmt
struct _My_Abstract_vmt
struct _My_Sensor
Typedefs
typedef struct _My_Sensor MySensor
typedef struct _My_vmt My_FctnTable
typedef struct _My_Abstract_vmt My_Abstract_FctnTable
Functions
void My_FctnInit (MySensor *this)
int My_Configure (MySensor *this)
int My_Request (MySensor *this)
int My_Collect (MySensor *this)
int My_Error (MySensor *this)
void My_VTinit (MySensor *)
int My_init (MySensor *)
int My_reset (MySensor *)
int My_getType (MySensor *)
MySensor * New_My_Sensor (int num)
Detailed Description
Declaration of My_Sensor struct, which derived from BaseSensor. Author: Anxin Bai
Typedef Documentation
typedef struct _My_Abstract_vmt My_Abstract_FctnTable
typedef struct _My_vmt My_FctnTable
typedef struct _My_Sensor MySensor
Function Documentation
int My_Collect (MySensor * this)
int My_Configure (MySensor * this)
int My_Error (MySensor * this)
void My_FctnInit (MySensor * this)
References My_vmt.
Referenced by New_My_Sensor().
int My_getType (MySensor *)
References TYPE_SENSOR.
int My_init (MySensor *)
int My_Request (MySensor * this)
int My_reset (MySensor *)
void My_VTinit (MySensor *)
References My_abstract_vmt.
Referenced by New_My_Sensor().
MySensor* New_My_Sensor (int num)
References _My_Sensor::inherited, My_FctnInit(), My_VTinit(), and _Base_Sensor::test_num.