C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/inc/Si7020.h File Reference
Si7020 Interface Library.
#include <stdint.h>
*
Macros
#define SI7020_ADDR 0x40
#define SI7020_REL_HUMIDITY_HOLD 0xE5
#define SI7020_REL_HUMIDITY_NONHOLD 0xF5
#define SI7020_TEMPERATURE_HOLD 0xE3
#define SI7020_TEMPERATURE_NOHOLD 0xF3
#define SI7020_RD_TEMP_PRE_RH 0xE0
#define SI7020_RESET 0xFE
#define SI7020_WR_RH_T_REG1 0xE6
#define SI7020_RD_RH_T_REG1 0xE7
#define SI7020_WR_HEAT_CTR_REG 0x51
#define SI7020_RD_HEAT_CTR_REG 0x11
#define SI7020_ELCID_1ST_BYTE 0xFA
#define SI7020_ELCID_2ND_BYTE 0xFC
#define SI7020_FIRMWARE_REV 0x84
#define SHIFTED_DIVISOR 0x988000
Functions
char Si7020_init ()
Initializes the Si7020.
char Si7020_readHumidity (unsigned char *, char)
Read humidity from Si7020.
char Si7020_readTemperature (unsigned char *, char)
Read temperature from Si7020.
float Si7020_calHumidity (unsigned char *)
Calculate humidity from Si7020.
float Si7020_calTemperature (unsigned char *)
Calculate temperature from Si7020.
Detailed Description
Si7020 Interface Library. Created: 3/27/2015 11:14:55 Author: Hui Shi
Macro Definition Documentation
#define SHIFTED_DIVISOR 0x988000
#define SI7020_ADDR 0x40
Referenced by Si7020_readHumidity(), and Si7020_readTemperature().
#define SI7020_ELCID_1ST_BYTE 0xFA
#define SI7020_ELCID_2ND_BYTE 0xFC
#define SI7020_FIRMWARE_REV 0x84
#define SI7020_RD_HEAT_CTR_REG 0x11
#define SI7020_RD_RH_T_REG1 0xE7
#define SI7020_RD_TEMP_PRE_RH 0xE0
#define SI7020_REL_HUMIDITY_HOLD 0xE5
Status Codes
Referenced by Si7020_readHumidity().
#define SI7020_REL_HUMIDITY_NONHOLD 0xF5
#define SI7020_RESET 0xFE
#define SI7020_TEMPERATURE_HOLD 0xE3
Referenced by Si7020_readTemperature().
#define SI7020_TEMPERATURE_NOHOLD 0xF3
#define SI7020_WR_HEAT_CTR_REG 0x51
#define SI7020_WR_RH_T_REG1 0xE6
Function Documentation
float Si7020_calHumidity (unsigned char * data)
Calculate humidity from Si7020.
Returns
humidity value
float Si7020_calTemperature (unsigned char * data)
Calculate temperature from Si7020.
Returns
temperature value
char Si7020_init ()
Initializes the Si7020.
Returns
status zero
char Si7020_readHumidity (unsigned char * data, char length)
Read humidity from Si7020.
Returns
status one if successfully read and crc check, otherwise return zero
References check_crc(), SI7020_ADDR, SI7020_REL_HUMIDITY_HOLD, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_ACK, TWI_SENT_ACK, TWI_SLAR_ACK, TWI_Stop(), and TWI_WriteByte().
char Si7020_readTemperature (unsigned char * data, char length)
Read temperature from Si7020.
Returns
status one if successfully read and crc check, otherwise return zero
References check_crc(), SI7020_ADDR, SI7020_TEMPERATURE_HOLD, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_ACK, TWI_SENT_ACK, TWI_SLAR_ACK, TWI_Stop(), and TWI_WriteByte().