C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/src/Si7020.c File Reference
#include `devices/inc/Si7020.h`
*
#include `drivers/inc/TWI.h`
*
#include <math.h>
*
Functions
char Si7020_init ()
Initializes the Si7020.
char Si7020_readHumidity (unsigned char *data, char length)
Read humidity from Si7020.
float Si7020_calHumidity (unsigned char *data)
Calculate humidity from Si7020.
char Si7020_readTemperature (unsigned char *data, char length)
Read temperature from Si7020.
float Si7020_calTemperature (unsigned char *data)
Calculate temperature from Si7020.
Detailed Description
Created: 3/27/2015 11:14:55 Author: Hui Shi
Function Documentation
float Si7020_calHumidity (unsigned char * data)
Calculate humidity from Si7020.
Returns
humidity value
float Si7020_calTemperature (unsigned char * data)
Calculate temperature from Si7020.
Returns
temperature value
char Si7020_init ()
Initializes the Si7020.
Returns
status zero
char Si7020_readHumidity (unsigned char * data, char length)
Read humidity from Si7020.
Returns
status one if successfully read and crc check, otherwise return zero
References check_crc(), SI7020_ADDR, SI7020_REL_HUMIDITY_HOLD, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_ACK, TWI_SENT_ACK, TWI_SLAR_ACK, TWI_Stop(), and TWI_WriteByte().
char Si7020_readTemperature (unsigned char * data, char length)
Read temperature from Si7020.
Returns
status one if successfully read and crc check, otherwise return zero
References check_crc(), SI7020_ADDR, SI7020_TEMPERATURE_HOLD, status, TWI_BeginRead(), TWI_BeginWrite(), TWI_Read(), TWI_REC_ACK, TWI_SENT_ACK, TWI_SLAR_ACK, TWI_Stop(), and TWI_WriteByte().