C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/devices/src/TGS2600.c File Reference
Figaro TGS2600 air quality sensor implementation.
#include `utilities/inc/common.h`
*
#include `devices/inc/TGS2600.h`
*
#include `drivers/inc/ADC.h`
*
#include `drivers/inc/PWR.h`
*
Functions
void TGS2600_Init (void)
void TGS2600_TurnOn (void)
void TGS2600_TurnOff (void)
float TGS2600_GetResistance (void)
Detailed Description
Figaro TGS2600 air quality sensor implementation. Created: 4/10/2015 11:03:19 Author: Camden
Function Documentation
float TGS2600_GetResistance (void)
References ADC1, ADC_Convert(), ADC_Reference(), and REFERENCE_AREF.
void TGS2600_Init (void)
References TGS2600_TurnOn().
void TGS2600_TurnOff (void)
void TGS2600_TurnOn (void)
Referenced by TGS2600_Init().