C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/drivers/inc/TWI.h File Reference
TWI hardware interface in master mode.
#include <stdbool.h>
*
Macros
TWI Status Codes
All the codes that could be given via TWSR
#define TWI_BUS_ERROR 0x00
Bus error due to illegal START or STOP condition.
#define TWI_START 0x08
A START condition has been transmitted.
#define TWI_REPEAT_START 0x10
A repeated START condition has been transmitted.
#define TWI_SLAW_ACK 0x18
SLA+W has been transmitted; ACK has been received.
#define TWI_SLAW_NACK 0x20
SLA+W has been transmitted; NOT ACK has been received.
#define TWI_SENT_ACK 0x28
Data byte has been transmitted; ACK has been received.
#define TWI_SENT_NACK 0x30
Data byte has been transmitted; NOT ACK has been received.
#define TWI_SLAW_LOST 0x38
Arbitration Lost.
#define TWI_SLAR_ACK 0x40
SLA+R has been transmitted; ACK has been received.
#define TWI_SLAR_NACK 0x48
SLA+R has been transmitted; NOT ACK has been received.
#define TWI_REC_ACK 0x50
Data byte has been received; ACK has been returned.
#define TWI_REC_NACK 0x58
Data byte has been received; NOT ACK has been returned.
#define TWI_OWN_SLAW_ACK 0x60
Own SLA+W has been received; ACK has been returned.
#define TWI_SLAR_LOST 0x68
Arbitration Lost.
#define TWI_GEN_CALL_ACK 0x70
General call address has been received; ACK has been returned.
#define TWI_GEN_LOST_ACK 0x78
Arbitration Lost.
#define TWI_SLA_REC_ACK 0x80
Previously addressed with own SLA+W; data has been received; ACK has been returned.
#define TWI_SLA_REC_NACK 0x88
Previously addressed with own SLA+W; data has been received; NOT ACK has been returned.
#define TWI_GEN_REC_ACK 0x90
Previously addressed with general call; data has been received; ACK has been returned.
#define TWI_GEN_REC_NACK 0x98
Previously addressed with general call; data has been received; NOT ACK has been returned.
#define TWI_SLA_STOP 0xA0
A STOP condition or repeated START condition has been received while still addressed as Slave.
#define TWI_OWN_SLAR_ACK 0xA8
Own SLA+R has been received; ACK has been returned.
#define TWI_O_SLAR_LOST_ACK 0xB0
Arbitration Lost.
#define TWI_TWDR_SENT_ACK 0xB8
Data byte in TWDR has been transmitted; ACK has been received.
#define TWI_TWDR_SENT_NACK 0xC0
Data byte in TWDR has been transmitted; NO ACK has been received.
#define TWI_LAST_TWDR_SENT 0xC8
Last data byte in TWDR has been transmitted (TWEA = 0); ACK has been received.
#define TWI_NO_INFO 0xF8
No relevant state information available; TWINT = 0.
TWI Masks
Mask off TWSR with 0xF8 (TWSR_MASK) to get status bits
#define TWSR_MASK 0xF8
Mask off with TWSR to get status codes.
#define SLAW_MASK 0xFE
AND i2c address with this to reset R/W bit.
#define SLAR_MASK 0x01
OR i2c address with this to set R/W bit.
Functions
char TWI_Write (unsigned char *data, int amount)
Writes multiple bytes to the TWI bus.
char TWI_Read (unsigned char *data, int amount, bool ack)
Reads multiple bytes from the TWI bus.
char TWI_Stop (void)
Sends a Stop bit, be sure to send a Start bit before future interactions on the bus.
char TWI_ReadNack (unsigned char *data)
Receives a byte over TWI and returns a NACK.
char TWI_ReadAck (unsigned char *data)
Receives a byte over TWI and returns an ACK.
char TWI_WriteByte (unsigned char data)
Sends a byte over TWI.
char TWI_BeginRead (unsigned char address)
Starts a transmission over the TWI Bus.
char TWI_BeginWrite (unsigned char address)
Starts a transmission over the TWI Bus.
char TWI_Init (unsigned long freq)
Initializes the 2-wire Serial Interface as a master.
Detailed Description
TWI hardware interface in master mode. Created: 2/7/2015 21:12:13 Author: Camden
Macro Definition Documentation
#define SLAR_MASK 0x01
OR i2c address with this to set R/W bit.
Referenced by TWI_BeginRead().
#define SLAW_MASK 0xFE
AND i2c address with this to reset R/W bit.
Referenced by TWI_BeginWrite().
#define TWI_BUS_ERROR 0x00
Bus error due to illegal START or STOP condition.
#define TWI_GEN_CALL_ACK 0x70
General call address has been received; ACK has been returned.
#define TWI_GEN_LOST_ACK 0x78
Arbitration Lost.
Arbitration lost in SLA+R/W as Master; general call address has been received; ACK has been returned.
#define TWI_GEN_REC_ACK 0x90
Previously addressed with general call; data has been received; ACK has been returned.
#define TWI_GEN_REC_NACK 0x98
Previously addressed with general call; data has been received; NOT ACK has been returned.
#define TWI_LAST_TWDR_SENT 0xC8
Last data byte in TWDR has been transmitted (TWEA = 0); ACK has been received.
#define TWI_NO_INFO 0xF8
No relevant state information available; TWINT = 0.
#define TWI_O_SLAR_LOST_ACK 0xB0
Arbitration Lost.
Arbitration lost in SLA+R/W as Master; own SLA+R has been received; ACK has been returned.
#define TWI_OWN_SLAR_ACK 0xA8
Own SLA+R has been received; ACK has been returned.
#define TWI_OWN_SLAW_ACK 0x60
Own SLA+W has been received; ACK has been returned.
#define TWI_REC_ACK 0x50
Data byte has been received; ACK has been returned.
Referenced by K30_readCO2(), Si7020_readHumidity(), Si7020_readTemperature(), and TWI_Read().
#define TWI_REC_NACK 0x58
Data byte has been received; NOT ACK has been returned.
Referenced by BMP280_ReadBytes().
#define TWI_REPEAT_START 0x10
A repeated START condition has been transmitted.
Referenced by TWI_BeginRead(), and TWI_BeginWrite().
#define TWI_SENT_ACK 0x28
Data byte has been transmitted; ACK has been received.
Referenced by BMP280_WriteBytes(), K30_readCO2(), Si7020_readHumidity(), Si7020_readTemperature(), and TWI_Write().
#define TWI_SENT_NACK 0x30
Data byte has been transmitted; NOT ACK has been received.
#define TWI_SLA_REC_ACK 0x80
Previously addressed with own SLA+W; data has been received; ACK has been returned.
#define TWI_SLA_REC_NACK 0x88
Previously addressed with own SLA+W; data has been received; NOT ACK has been returned.
#define TWI_SLA_STOP 0xA0
A STOP condition or repeated START condition has been received while still addressed as Slave.
#define TWI_SLAR_ACK 0x40
SLA+R has been transmitted; ACK has been received.
Referenced by BMP280_ReadBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
#define TWI_SLAR_LOST 0x68
Arbitration Lost.
Arbitration lost in SLA+R/W as Master; own SLA+W has been received; ACK has been returned.
#define TWI_SLAR_NACK 0x48
SLA+R has been transmitted; NOT ACK has been received.
#define TWI_SLAW_ACK 0x18
SLA+W has been transmitted; ACK has been received.
Referenced by K30_readCO2().
#define TWI_SLAW_LOST 0x38
Arbitration Lost.
Arbitration lost in SLA+W or data bytes (Transmitter); Arbitration lost in SLA+R or NOT ACK bit (Receiver).
#define TWI_SLAW_NACK 0x20
SLA+W has been transmitted; NOT ACK has been received.
#define TWI_START 0x08
A START condition has been transmitted.
Referenced by TWI_BeginRead(), and TWI_BeginWrite().
#define TWI_TWDR_SENT_ACK 0xB8
Data byte in TWDR has been transmitted; ACK has been received.
#define TWI_TWDR_SENT_NACK 0xC0
Data byte in TWDR has been transmitted; NO ACK has been received.
#define TWSR_MASK 0xF8
Mask off with TWSR to get status codes.
Referenced by BMP280_ReadBytes(), TWI_BeginRead(), TWI_BeginWrite(), TWI_ReadAck(), TWI_ReadNack(), and TWI_WriteByte().
Function Documentation
char TWI_BeginRead (unsigned char address)
Starts a transmission over the TWI Bus.
Parameters
in address Address of device to send to
Returns
Status code, TWI_SLAR_ACK on success, other code otherwise
References SLAR_MASK, TWI_REPEAT_START, TWI_START, TWI_WriteByte(), and TWSR_MASK.
Referenced by BMP280_ReadBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_BeginWrite (unsigned char address)
Starts a transmission over the TWI Bus.
Parameters
in address Address of device to send to
Returns
Status code, TWI_SLAW_ACK on success, other code otherwise
References SLAW_MASK, TWI_REPEAT_START, TWI_START, TWI_WriteByte(), and TWSR_MASK.
Referenced by BMP280_ReadBytes(), BMP280_WriteBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_Init (unsigned long freq)
Initializes the 2-wire Serial Interface as a master.
Parameters
in freq SCL frequency (Do not exceed 400kHz)
Returns
Status (0 on failure, nonzero otherwise)
References F_CPU.
Referenced by APP_Init().
char TWI_Read (unsigned char * data, int amount, bool ack)
Reads multiple bytes from the TWI bus.
When using this function, be sure to send a START first; this only automates calls to TWI_ReadAck and/or TWI_ReadNack.
Does not contain buffer overrun protection.
Parameters
out *data Pointer to an array to store the bytes
in amount Number of bytes to recieve
in whether or not to send an ACK on the last byte, sends NACK if false
Returns
Status code, TWI_REC_ACK or TWI_REC_NACK on success depending on function arguments
See also
TWI_BeginRead
References status, TWI_ReadAck(), TWI_ReadNack(), and TWI_REC_ACK.
Referenced by BMP280_ReadBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_ReadAck (unsigned char * data)
Receives a byte over TWI and returns an ACK.
Parameters
out *data pointer to a byte to store the received byte in
Returns
Status code, TWI_REC_ACK on success, other code otherwise
References TWSR_MASK.
Referenced by TWI_Read().
char TWI_ReadNack (unsigned char * data)
Receives a byte over TWI and returns a NACK.
Parameters
out *data pointer to a byte to store the received byte in
Returns
Status code, TWI_REC_NACK on success, other code otherwise
References TWSR_MASK.
Referenced by TWI_Read().
char TWI_Stop (void)
Sends a Stop bit, be sure to send a Start bit before future interactions on the bus.
Returns
Status code, should always be nonzero
Referenced by BMP280_ReadBytes(), BMP280_WriteBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_Write (unsigned char * data, int amount)
Writes multiple bytes to the TWI bus.
When using this function, be sure to send a START first; this only automates calls to TWI_Write.
Does not contain buffer overrun protection. Function will return if a NACK is received partway through. If you don't expect a NACK, be sure to check for it anyway.
Parameters
in *data Pointer to an array of bytes to send
in amount Number of bytes to send
Returns
Status code, TWI_REC_ACK or TWI_REC_NACK on success
See also
TWI_BeginWrite
References status, TWI_SENT_ACK, and TWI_WriteByte().
Referenced by BMP280_WriteBytes(), and K30_readCO2().
char TWI_WriteByte (unsigned char data)
Sends a byte over TWI.
When checking the status code, bear in mind that it could be an ACK or a NACK depending on what the slave is expecting/doing.
Parameters
in data byte to send
Returns
Status code, TWI_SENT_ACK or TWI_SENT_NACK on success
References TWSR_MASK.
Referenced by BMP280_ReadBytes(), Si7020_readHumidity(), Si7020_readTemperature(), TWI_BeginRead(), TWI_BeginWrite(), and TWI_Write().