C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/drivers/src/TWI.c File Reference
TWI hardware interface library implementation in master mode.
#include `drivers/inc/TWI.h`
*
#include `drivers/inc/usart0.h`
*
#include <avr/io.h>
*
#include <stdbool.h>
*
#include <util/delay.h>
*
Functions
char TWI_Init (unsigned long freq)
Initializes the 2-wire Serial Interface as a master.
char TWI_BeginWrite (unsigned char address)
Starts a transmission over the TWI Bus.
char TWI_BeginRead (unsigned char address)
Starts a transmission over the TWI Bus.
char TWI_WriteByte (unsigned char data)
Sends a byte over TWI.
char TWI_ReadAck (unsigned char *data)
Receives a byte over TWI and returns an ACK.
char TWI_ReadNack (unsigned char *data)
Receives a byte over TWI and returns a NACK.
char TWI_Stop (void)
Sends a Stop bit, be sure to send a Start bit before future interactions on the bus.
char TWI_Read (unsigned char *data, int amount, bool ack)
Reads multiple bytes from the TWI bus.
char TWI_Write (unsigned char *data, int amount)
Writes multiple bytes to the TWI bus.
Detailed Description
TWI hardware interface library implementation in master mode. Created: 2/7/2015 21:12:00 Author: Camden Miller
Function Documentation
char TWI_BeginRead (unsigned char address)
Starts a transmission over the TWI Bus.
Parameters
in address Address of device to send to
Returns
Status code, TWI_SLAR_ACK on success, other code otherwise
References SLAR_MASK, TWI_REPEAT_START, TWI_START, TWI_WriteByte(), and TWSR_MASK.
Referenced by BMP280_ReadBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_BeginWrite (unsigned char address)
Starts a transmission over the TWI Bus.
Parameters
in address Address of device to send to
Returns
Status code, TWI_SLAW_ACK on success, other code otherwise
References SLAW_MASK, TWI_REPEAT_START, TWI_START, TWI_WriteByte(), and TWSR_MASK.
Referenced by BMP280_ReadBytes(), BMP280_WriteBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_Init (unsigned long freq)
Initializes the 2-wire Serial Interface as a master.
Parameters
in freq SCL frequency (Do not exceed 400kHz)
Returns
Status (0 on failure, nonzero otherwise)
References F_CPU.
Referenced by APP_Init().
char TWI_Read (unsigned char * data, int amount, bool ack)
Reads multiple bytes from the TWI bus.
When using this function, be sure to send a START first; this only automates calls to TWI_ReadAck and/or TWI_ReadNack.
Does not contain buffer overrun protection.
Parameters
out *data Pointer to an array to store the bytes
in amount Number of bytes to recieve
in whether or not to send an ACK on the last byte, sends NACK if false
Returns
Status code, TWI_REC_ACK or TWI_REC_NACK on success depending on function arguments
See also
TWI_BeginRead
References status, TWI_ReadAck(), TWI_ReadNack(), and TWI_REC_ACK.
Referenced by BMP280_ReadBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_ReadAck (unsigned char * data)
Receives a byte over TWI and returns an ACK.
Parameters
out *data pointer to a byte to store the received byte in
Returns
Status code, TWI_REC_ACK on success, other code otherwise
References TWSR_MASK.
Referenced by TWI_Read().
char TWI_ReadNack (unsigned char * data)
Receives a byte over TWI and returns a NACK.
Parameters
out *data pointer to a byte to store the received byte in
Returns
Status code, TWI_REC_NACK on success, other code otherwise
References TWSR_MASK.
Referenced by TWI_Read().
char TWI_Stop (void)
Sends a Stop bit, be sure to send a Start bit before future interactions on the bus.
Returns
Status code, should always be nonzero
Referenced by BMP280_ReadBytes(), BMP280_WriteBytes(), K30_readCO2(), Si7020_readHumidity(), and Si7020_readTemperature().
char TWI_Write (unsigned char * data, int amount)
Writes multiple bytes to the TWI bus.
When using this function, be sure to send a START first; this only automates calls to TWI_Write.
Does not contain buffer overrun protection. Function will return if a NACK is received partway through. If you don't expect a NACK, be sure to check for it anyway.
Parameters
in *data Pointer to an array of bytes to send
in amount Number of bytes to send
Returns
Status code, TWI_REC_ACK or TWI_REC_NACK on success
See also
TWI_BeginWrite
References status, TWI_SENT_ACK, and TWI_WriteByte().
Referenced by BMP280_WriteBytes(), and K30_readCO2().
char TWI_WriteByte (unsigned char data)
Sends a byte over TWI.
When checking the status code, bear in mind that it could be an ACK or a NACK depending on what the slave is expecting/doing.
Parameters
in data byte to send
Returns
Status code, TWI_SENT_ACK or TWI_SENT_NACK on success
References TWSR_MASK.
Referenced by BMP280_ReadBytes(), Si7020_readHumidity(), Si7020_readTemperature(), TWI_BeginRead(), TWI_BeginWrite(), and TWI_Write().