C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/drivers/inc/int_timer.h File Reference
Example for Timers on AVR Devices.
#include `avr/io.h`
*
#include `avr/interrupt.h`
*
#include `scheduler/inc/scheduler.h`
*
Macros
#define ATMEL
#define APERIOD 8
Functions
void init_Event_Timer (void)
void general_set_timer (int period_number)
void init_set_timer (int period_number)
void set_timer (int period_number)
ISR (TIMER2_OVF_vect)
Detailed Description
Example for Timers on AVR Devices. Copyright (C) 2016 Atmel Corporation. All rights reserved.
Macro Definition Documentation
#define APERIOD 8
#define ATMEL
Function Documentation
void general_set_timer (int period_number)
void init_Event_Timer (void)
Referenced by main().
void init_set_timer (int period_number)
Referenced by main().
ISR (TIMER2_OVF_vect)
void set_timer (int period_number)
Referenced by handle_timeoutq_event().