C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/nwk/src/nwkRx.c File Reference
Receive routines implementation.
#include <stdlib.h>
*
#include <stdint.h>
*
#include <stdbool.h>
*
#include <string.h>
*
#include `phy.h`
*
#include `sysConfig.h`
*
#include `sysTimer.h`
*
#include `nwk.h`
*
#include `nwkTx.h`
*
#include `nwkFrame.h`
*
#include `nwkGroup.h`
*
#include `nwkRoute.h`
*
#include `nwkCommand.h`
*
#include `nwkSecurity.h`
*
#include `nwkRouteDiscovery.h`
*
Data Structures
struct NwkDuplicateRejectionEntry_t
Macros
#define NWK_RX_DUPLICATE_REJECTION_TIMER_INTERVAL 100
#define DUPLICATE_REJECTION_TTL ((NWK_DUPLICATE_REJECTION_TTL / NWK_RX_DUPLICATE_REJECTION_TIMER_INTERVAL) + 1)
#define NWK_SERVICE_ENDPOINT_ID 0
Typedefs
typedef struct
*
NwkDuplicateRejectionEntry_t NwkDuplicateRejectionEntry_t
Enumerations
enum {
*
NWK_RX_STATE_RECEIVED = 0x20,
NWK_RX_STATE_DECRYPT = 0x21,
NWK_RX_STATE_INDICATE = 0x22,
NWK_RX_STATE_ROUTE = 0x23,
*
NWK_RX_STATE_FINISH = 0x24
 }
Functions
static void nwkRxDuplicateRejectionTimerHandler (SYS_Timer_t *timer)
static bool nwkRxServiceDataInd (NWK_DataInd_t *ind)
void nwkRxInit (void)
Initializes the Rx module.
void PHY_DataInd (PHY_DataInd_t *ind)
static void nwkRxSendAck (NwkFrame_t *frame)
void NWK_SetAckControl (uint8_t control)
static bool nwkRxRejectDuplicate (NwkFrameHeader_t *header)
static void nwkRxHandleReceivedFrame (NwkFrame_t *frame)
static bool nwkRxIndicateFrame (NwkFrame_t *frame)
static void nwkRxHandleIndication (NwkFrame_t *frame)
void nwkRxTaskHandler (void)
Rx Module task handler.
Variables
static NwkDuplicateRejectionEntry_t nwkRxDuplicateRejectionTable [NWK_DUPLICATE_REJECTION_TABLE_SIZE]
static uint8_t nwkRxAckControl
static SYS_Timer_t nwkRxDuplicateRejectionTimer
Detailed Description
Receive routines implementation. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
nwkRx.c 9267 2014-03-18 21:46:19Z ataradov
Macro Definition Documentation
#define DUPLICATE_REJECTION_TTL ((NWK_DUPLICATE_REJECTION_TTL / NWK_RX_DUPLICATE_REJECTION_TIMER_INTERVAL) + 1)
Referenced by nwkRxRejectDuplicate().
#define NWK_RX_DUPLICATE_REJECTION_TIMER_INTERVAL 100
Referenced by nwkRxInit().
#define NWK_SERVICE_ENDPOINT_ID 0
Referenced by nwkRxInit().
Typedef Documentation
typedef struct NwkDuplicateRejectionEntry_t NwkDuplicateRejectionEntry_t
Enumeration Type Documentation
anonymous enum
Enumerator:
NWK_RX_STATE_RECEIVED
NWK_RX_STATE_DECRYPT
NWK_RX_STATE_INDICATE
NWK_RX_STATE_ROUTE
NWK_RX_STATE_FINISH
Function Documentation
void NWK_SetAckControl (uint8_t control)
References nwkRxAckControl.
static void nwkRxDuplicateRejectionTimerHandler (SYS_Timer_t * timer) [static]
References NWK_DUPLICATE_REJECTION_TABLE_SIZE, SYS_TimerStart(), and NwkDuplicateRejectionEntry_t::ttl.
Referenced by nwkRxInit().
static void nwkRxHandleIndication (NwkFrame_t * frame) [static]
References NwkIb_t::addr, NwkFrame_t::header, NwkFrameHeader_t::macDstAddr, NwkFrameHeader_t::macDstPanId, NWK_BROADCAST_ADDR, NWK_BROADCAST_PANID, NWK_RX_STATE_FINISH, NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkIb, nwkRxAckControl, nwkRxIndicateFrame(), nwkRxSendAck(), and NwkFrame_t::state.
Referenced by nwkRxTaskHandler().
static void nwkRxHandleReceivedFrame (NwkFrame_t * frame) [static]
References NwkIb_t::addr, NwkFrame_t::header, NwkFrameHeader_t::macDstAddr, NwkFrameHeader_t::macDstPanId, NwkFrameHeader_t::macSrcAddr, NwkFrameMulticastHeader_t::maxMemberRadius, NwkFrameMulticastHeader_t::maxNonMemberRadius, NwkFrameMulticastHeader_t::memberRadius, NwkFrameMulticastHeader_t::nonMemberRadius, NWK_BROADCAST_ADDR, NWK_BROADCAST_PANID, NWK_RX_STATE_DECRYPT, NWK_RX_STATE_FINISH, NWK_RX_STATE_INDICATE, NWK_RX_STATE_ROUTE, NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkIb, nwkRxRejectDuplicate(), NwkFrameHeader_t::nwkSrcAddr, nwkTxBroadcastFrame(), NwkFrame_t::payload, NwkFrame_t::rx, and NwkFrame_t::state.
Referenced by nwkRxTaskHandler().
static bool nwkRxIndicateFrame (NwkFrame_t * frame) [static]
References NWK_DataInd_t::data, NWK_DataInd_t::dstAddr, NWK_DataInd_t::dstEndpoint, NwkIb_t::endpoint, NwkFrame_t::header, NWK_DataInd_t::lqi, NwkFrameHeader_t::macDstPanId, NwkFrameHeader_t::macSrcAddr, NWK_BROADCAST_ADDR, NWK_BROADCAST_PANID, NWK_IND_OPT_ACK_REQUESTED, NWK_IND_OPT_BROADCAST, NWK_IND_OPT_BROADCAST_PAN_ID, NWK_IND_OPT_LINK_LOCAL, NWK_IND_OPT_LOCAL, NWK_IND_OPT_MULTICAST, NWK_IND_OPT_SECURED, NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkFramePayloadSize(), nwkIb, NwkFrameHeader_t::nwkSrcAddr, NWK_DataInd_t::options, NwkFrame_t::payload, NWK_DataInd_t::rssi, NwkFrame_t::rx, NWK_DataInd_t::size, NWK_DataInd_t::srcAddr, and NWK_DataInd_t::srcEndpoint.
Referenced by nwkRxHandleIndication().
void nwkRxInit (void)
Initializes the Rx module.
References SYS_Timer_t::handler, SYS_Timer_t::interval, SYS_Timer_t::mode, NWK_DUPLICATE_REJECTION_TABLE_SIZE, NWK_OpenEndpoint(), NWK_RX_DUPLICATE_REJECTION_TIMER_INTERVAL, NWK_SERVICE_ENDPOINT_ID, nwkRxDuplicateRejectionTimerHandler(), nwkRxServiceDataInd(), and SYS_TIMER_INTERVAL_MODE.
Referenced by NWK_Init().
static bool nwkRxRejectDuplicate (NwkFrameHeader_t * header) [static]
References NwkIb_t::addr, DUPLICATE_REJECTION_TTL, NwkFrameHeader_t::macDstAddr, NwkDuplicateRejectionEntry_t::mask, NWK_DUPLICATE_REJECTION_TABLE_SIZE, NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkIb, NwkFrameHeader_t::nwkSeq, NwkFrameHeader_t::nwkSrcAddr, NwkDuplicateRejectionEntry_t::seq, NwkDuplicateRejectionEntry_t::src, SYS_TimerStart(), and NwkDuplicateRejectionEntry_t::ttl.
Referenced by nwkRxHandleReceivedFrame().
static void nwkRxSendAck (NwkFrame_t * frame) [static]
References NwkCommandAck_t::control, NwkFrame_t::header, NwkCommandAck_t::id, NWK_COMMAND_ACK, NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkFrameAlloc(), nwkFrameCommandInit(), nwkRxAckControl, NwkFrameHeader_t::nwkSeq, NwkFrameHeader_t::nwkSrcAddr, nwkTxFrame(), NwkFrame_t::payload, NwkCommandAck_t::seq, NwkFrame_t::size, and NwkFrame_t::tx.
Referenced by nwkRxHandleIndication().
static bool nwkRxServiceDataInd (NWK_DataInd_t * ind) [static]
References NWK_DataInd_t::data, NWK_COMMAND_ACK, NWK_COMMAND_ROUTE_ERROR, NWK_COMMAND_ROUTE_REPLY, NWK_COMMAND_ROUTE_REQUEST, NWK_IND_OPT_SECURED, nwkTxAckReceived(), NWK_DataInd_t::options, and NWK_DataInd_t::size.
Referenced by nwkRxInit().
void nwkRxTaskHandler (void)
Rx Module task handler.
References NWK_RX_STATE_DECRYPT, NWK_RX_STATE_FINISH, NWK_RX_STATE_INDICATE, NWK_RX_STATE_RECEIVED, NWK_RX_STATE_ROUTE, nwkFrameFree(), nwkFrameNext(), nwkRxHandleIndication(), nwkRxHandleReceivedFrame(), and NwkFrame_t::state.
Referenced by NWK_TaskHandler().
void PHY_DataInd (PHY_DataInd_t * ind)
References PHY_DataInd_t::data, NwkFrame_t::data, PHY_DataInd_t::lqi, NWK_RX_STATE_RECEIVED, nwkFrameAlloc(), PHY_DataInd_t::rssi, NwkFrame_t::rx, PHY_DataInd_t::size, NwkFrame_t::size, and NwkFrame_t::state.
Variable Documentation
uint8_t nwkRxAckControl [static]
Referenced by NWK_SetAckControl(), nwkRxHandleIndication(), and nwkRxSendAck().
NwkDuplicateRejectionEntry_t nwkRxDuplicateRejectionTable[NWK_DUPLICATE_REJECTION_TABLE_SIZE] [static]
SYS_Timer_t nwkRxDuplicateRejectionTimer [static]