C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/nwk/src/nwkTx.c File Reference
Transmit routines implementation.
#include <stdlib.h>
*
#include <stdint.h>
*
#include <stdbool.h>
*
#include <string.h>
*
#include `phy.h`
*
#include `sysConfig.h`
*
#include `sysTimer.h`
*
#include `nwk.h`
*
#include `nwkTx.h`
*
#include `nwkFrame.h`
*
#include `nwkRoute.h`
*
#include `nwkCommand.h`
*
#include `nwkSecurity.h`
*
Macros
#define NWK_TX_ACK_WAIT_TIMER_INTERVAL 50
#define NWK_TX_DELAY_TIMER_INTERVAL 10
#define NWK_TX_DELAY_JITTER_MASK 0x07
Enumerations
enum {
*
NWK_TX_STATE_ENCRYPT = 0x10,
NWK_TX_STATE_WAIT_DELAY = 0x11,
NWK_TX_STATE_DELAY = 0x12,
NWK_TX_STATE_SEND = 0x13,
*
NWK_TX_STATE_WAIT_CONF = 0x14,
NWK_TX_STATE_SENT = 0x15,
NWK_TX_STATE_WAIT_ACK = 0x16,
NWK_TX_STATE_CONFIRM = 0x17
 }
Functions
static void nwkTxAckWaitTimerHandler (SYS_Timer_t *timer)
static void nwkTxDelayTimerHandler (SYS_Timer_t *timer)
void nwkTxInit (void)
Initializes the Tx module.
void nwkTxFrame (NwkFrame_t *frame)
void nwkTxBroadcastFrame (NwkFrame_t *frame)
bool nwkTxAckReceived (NWK_DataInd_t *ind)
void nwkTxConfirm (NwkFrame_t *frame, uint8_t status)
static uint8_t nwkTxConvertPhyStatus (uint8_t status)
void PHY_DataConf (uint8_t status)
void nwkTxTaskHandler (void)
Tx Module task handler.
Variables
static NwkFrame_t * nwkTxPhyActiveFrame
static SYS_Timer_t nwkTxAckWaitTimer
static SYS_Timer_t nwkTxDelayTimer
Detailed Description
Transmit routines implementation. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
nwkTx.c 9267 2014-03-18 21:46:19Z ataradov
Macro Definition Documentation
#define NWK_TX_ACK_WAIT_TIMER_INTERVAL 50
Referenced by nwkTxInit(), and nwkTxTaskHandler().
#define NWK_TX_DELAY_JITTER_MASK 0x07
Referenced by nwkTxBroadcastFrame(), and nwkTxFrame().
#define NWK_TX_DELAY_TIMER_INTERVAL 10
Referenced by nwkTxInit().
Enumeration Type Documentation
anonymous enum
Enumerator:
NWK_TX_STATE_ENCRYPT
NWK_TX_STATE_WAIT_DELAY
NWK_TX_STATE_DELAY
NWK_TX_STATE_SEND
NWK_TX_STATE_WAIT_CONF
NWK_TX_STATE_SENT
NWK_TX_STATE_WAIT_ACK
NWK_TX_STATE_CONFIRM
Function Documentation
bool nwkTxAckReceived (NWK_DataInd_t * ind)
References NwkCommandAck_t::control, NWK_DataInd_t::data, NWK_TX_STATE_CONFIRM, NWK_TX_STATE_WAIT_ACK, nwkFrameNext(), NwkCommandAck_t::seq, NWK_DataInd_t::size, and NwkFrame_t::state.
Referenced by nwkRxServiceDataInd().
static void nwkTxAckWaitTimerHandler (SYS_Timer_t * timer) [static]
References NWK_NO_ACK_STATUS, NWK_TX_STATE_WAIT_ACK, nwkFrameNext(), nwkTxConfirm(), NwkFrame_t::state, SYS_TimerStart(), and NwkFrame_t::tx.
Referenced by nwkTxInit().
void nwkTxBroadcastFrame (NwkFrame_t * frame)
References NwkIb_t::addr, NwkFrame_t::data, NwkFrame_t::header, NwkFrameHeader_t::macDstAddr, NwkFrameHeader_t::macDstPanId, NwkFrameHeader_t::macFcf, NwkFrameHeader_t::macSeq, NwkIb_t::macSeqNum, NwkFrameHeader_t::macSrcAddr, NWK_BROADCAST_ADDR, NWK_SUCCESS_STATUS, NWK_TX_DELAY_JITTER_MASK, NWK_TX_STATE_DELAY, nwkFrameAlloc(), nwkIb, NwkFrame_t::size, NwkFrame_t::state, and NwkFrame_t::tx.
Referenced by nwkRxHandleReceivedFrame().
void nwkTxConfirm (NwkFrame_t * frame, uint8_t status)
References NWK_TX_STATE_CONFIRM, NwkFrame_t::state, status, and NwkFrame_t::tx.
Referenced by nwkTxAckWaitTimerHandler().
static uint8_t nwkTxConvertPhyStatus (uint8_t status) [static]
References NWK_ERROR_STATUS, NWK_PHY_CHANNEL_ACCESS_FAILURE_STATUS, NWK_PHY_NO_ACK_STATUS, NWK_SUCCESS_STATUS, PHY_STATUS_CHANNEL_ACCESS_FAILURE, PHY_STATUS_NO_ACK, and PHY_STATUS_SUCCESS.
Referenced by PHY_DataConf().
static void nwkTxDelayTimerHandler (SYS_Timer_t * timer) [static]
References NWK_TX_STATE_SEND, NWK_TX_STATE_WAIT_DELAY, nwkFrameNext(), NwkFrame_t::state, SYS_TimerStart(), and NwkFrame_t::tx.
Referenced by nwkTxInit().
void nwkTxFrame (NwkFrame_t * frame)
References NwkIb_t::addr, NwkFrame_t::header, NwkFrameHeader_t::macDstAddr, NwkFrameHeader_t::macDstPanId, NwkFrameHeader_t::macFcf, NwkFrameHeader_t::macSeq, NwkIb_t::macSeqNum, NwkFrameHeader_t::macSrcAddr, NWK_BROADCAST_ADDR, NWK_BROADCAST_PANID, NWK_SUCCESS_STATUS, NWK_TX_CONTROL_BROADCAST_PAN_ID, NWK_TX_CONTROL_DIRECT_LINK, NWK_TX_CONTROL_ROUTING, NWK_TX_DELAY_JITTER_MASK, NWK_TX_STATE_DELAY, NWK_TX_STATE_ENCRYPT, NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkIb, NwkIb_t::panId, NwkFrame_t::state, and NwkFrame_t::tx.
Referenced by nwkDataReqSendFrame(), and nwkRxSendAck().
void nwkTxInit (void)
Initializes the Tx module.
References SYS_Timer_t::handler, SYS_Timer_t::interval, SYS_Timer_t::mode, NWK_TX_ACK_WAIT_TIMER_INTERVAL, NWK_TX_DELAY_TIMER_INTERVAL, nwkTxAckWaitTimerHandler(), nwkTxDelayTimerHandler(), and SYS_TIMER_INTERVAL_MODE.
Referenced by NWK_Init().
void nwkTxTaskHandler (void)
Tx Module task handler.
References NwkIb_t::addr, NwkFrame_t::data, NwkFrame_t::header, NwkIb_t::lock, NWK_ACK_WAIT_TIME, NWK_SUCCESS_STATUS, NWK_TX_ACK_WAIT_TIMER_INTERVAL, NWK_TX_STATE_CONFIRM, NWK_TX_STATE_DELAY, NWK_TX_STATE_ENCRYPT, NWK_TX_STATE_SEND, NWK_TX_STATE_SENT, NWK_TX_STATE_WAIT_ACK, NWK_TX_STATE_WAIT_CONF, NWK_TX_STATE_WAIT_DELAY, NwkFrameHeader_t::nwkFcf, nwkFrameFree(), nwkFrameNext(), nwkIb, NwkFrameHeader_t::nwkSrcAddr, PHY_DataReq(), NwkFrame_t::size, NwkFrame_t::state, SYS_TimerStart(), and NwkFrame_t::tx.
Referenced by NWK_TaskHandler().
void PHY_DataConf (uint8_t status)
References NwkIb_t::lock, NWK_TX_STATE_SENT, nwkIb, nwkTxConvertPhyStatus(), NwkFrame_t::state, and NwkFrame_t::tx.
Variable Documentation
SYS_Timer_t nwkTxAckWaitTimer [static]
SYS_Timer_t nwkTxDelayTimer [static]
NwkFrame_t* nwkTxPhyActiveFrame [static]