C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/nwk/src/nwkDataReq.c File Reference
NWK_DataReq() implementation.
#include <stdlib.h>
*
#include <stdint.h>
*
#include <stdbool.h>
*
#include <string.h>
*
#include `sysConfig.h`
*
#include `nwk.h`
*
#include `nwkTx.h`
*
#include `nwkFrame.h`
*
#include `nwkGroup.h`
*
#include `nwkDataReq.h`
*
Enumerations
enum { NWK_DATA_REQ_STATE_INITIAL,
NWK_DATA_REQ_STATE_WAIT_CONF,
NWK_DATA_REQ_STATE_CONFIRM
 }
Functions
static void nwkDataReqTxConf (NwkFrame_t *frame)
Frame transmission confirmation handler.
void nwkDataReqInit (void)
Initializes the Data Request module.
void NWK_DataReq (NWK_DataReq_t *req)
Adds request req to the queue of outgoing requests.
static void nwkDataReqSendFrame (NWK_DataReq_t *req)
Prepares and send outgoing frame based on the request req parameters.
static void nwkDataReqConfirm (NWK_DataReq_t *req)
Confirms request to the application and remove it from the queue.
void nwkDataReqTaskHandler (void)
Data Request module task handler.
Variables
static NWK_DataReq_t * nwkDataReqQueue
Detailed Description
NWK_DataReq() implementation. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
nwkDataReq.c 9267 2014-03-18 21:46:19Z ataradov
Enumeration Type Documentation
anonymous enum
Enumerator:
NWK_DATA_REQ_STATE_INITIAL
NWK_DATA_REQ_STATE_WAIT_CONF
NWK_DATA_REQ_STATE_CONFIRM
Function Documentation
void NWK_DataReq (NWK_DataReq_t * req)
Adds request req to the queue of outgoing requests.
Parameters
in req Pointer to the request parameters
References NWK_DataReq_t::frame, NwkIb_t::lock, NWK_DataReq_t::next, NWK_DATA_REQ_STATE_INITIAL, NWK_SUCCESS_STATUS, nwkDataReqQueue, nwkIb, NWK_DataReq_t::state, and NWK_DataReq_t::status.
static void nwkDataReqConfirm (NWK_DataReq_t * req) [static]
Confirms request to the application and remove it from the queue.
Parameters
in req Pointer to the request parameters
References NWK_DataReq_t::confirm, NwkIb_t::lock, NWK_DataReq_t::next, nwkDataReqQueue, and nwkIb.
Referenced by nwkDataReqTaskHandler().
void nwkDataReqInit (void)
Initializes the Data Request module.
Referenced by NWK_Init().
static void nwkDataReqSendFrame (NWK_DataReq_t * req) [static]
Prepares and send outgoing frame based on the request req parameters.
Parameters
in req Pointer to the request parameters
References NwkIb_t::addr, NWK_DataReq_t::data, NWK_DataReq_t::dstAddr, NWK_DataReq_t::dstEndpoint, NWK_DataReq_t::frame, NwkFrame_t::header, NwkFrameMulticastHeader_t::maxMemberRadius, NwkFrameMulticastHeader_t::maxNonMemberRadius, NwkFrameMulticastHeader_t::memberRadius, NwkFrameMulticastHeader_t::nonMemberRadius, NWK_DATA_REQ_STATE_CONFIRM, NWK_DATA_REQ_STATE_WAIT_CONF, NWK_OPT_ACK_REQUEST, NWK_OPT_BROADCAST_PAN_ID, NWK_OPT_ENABLE_SECURITY, NWK_OPT_LINK_LOCAL, NWK_OPT_MULTICAST, NWK_OUT_OF_MEMORY_STATUS, NWK_TX_CONTROL_BROADCAST_PAN_ID, nwkDataReqTxConf(), NwkFrameHeader_t::nwkDstAddr, NwkFrameHeader_t::nwkFcf, nwkFrameAlloc(), nwkIb, NwkFrameHeader_t::nwkSeq, NwkIb_t::nwkSeqNum, NwkFrameHeader_t::nwkSrcAddr, nwkTxFrame(), NWK_DataReq_t::options, NwkFrame_t::payload, NWK_DataReq_t::size, NwkFrame_t::size, NWK_DataReq_t::srcEndpoint, NWK_DataReq_t::state, NWK_DataReq_t::status, and NwkFrame_t::tx.
Referenced by nwkDataReqTaskHandler().
void nwkDataReqTaskHandler (void)
Data Request module task handler.
References NWK_DataReq_t::next, NWK_DATA_REQ_STATE_CONFIRM, NWK_DATA_REQ_STATE_INITIAL, NWK_DATA_REQ_STATE_WAIT_CONF, nwkDataReqConfirm(), and nwkDataReqSendFrame().
Referenced by NWK_TaskHandler().
static void nwkDataReqTxConf (NwkFrame_t * frame) [static]
Frame transmission confirmation handler.
Parameters
in frame Pointer to the sent frame
References NWK_DataReq_t::next, NWK_DATA_REQ_STATE_CONFIRM, nwkFrameFree(), and NwkFrame_t::tx.
Referenced by nwkDataReqSendFrame().
Variable Documentation
NWK_DataReq_t* nwkDataReqQueue [static]
Referenced by NWK_DataReq(), and nwkDataReqConfirm().