C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/nwk/inc/nwkRx.h File Reference
Receive routines interface.
#include <stdint.h>
*
#include `sysTypes.h`
*
#include `nwkFrame.h`
*
Data Structures
struct NWK_DataInd_t
Typedefs
typedef struct NWK_DataInd_t NWK_DataInd_t
Enumerations
enum {
*
NWK_IND_OPT_ACK_REQUESTED = 1 << 0,
NWK_IND_OPT_SECURED = 1 << 1,
NWK_IND_OPT_BROADCAST = 1 << 2,
NWK_IND_OPT_LOCAL = 1 << 3,
*
NWK_IND_OPT_BROADCAST_PAN_ID = 1 << 4,
NWK_IND_OPT_LINK_LOCAL = 1 << 5,
NWK_IND_OPT_MULTICAST = 1 << 6
 }
Functions
void NWK_SetAckControl (uint8_t control)
void nwkRxInit (void)
Initializes the Rx module.
void nwkRxDecryptConf (NwkFrame_t *frame, bool status)
void nwkRxTaskHandler (void)
Rx Module task handler.
Detailed Description
Receive routines interface. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
nwkRx.h 9267 2014-03-18 21:46:19Z ataradov
Typedef Documentation
typedef struct NWK_DataInd_t NWK_DataInd_t
Enumeration Type Documentation
anonymous enum
Enumerator:
NWK_IND_OPT_ACK_REQUESTED
NWK_IND_OPT_SECURED
NWK_IND_OPT_BROADCAST
NWK_IND_OPT_LOCAL
NWK_IND_OPT_BROADCAST_PAN_ID
NWK_IND_OPT_LINK_LOCAL
NWK_IND_OPT_MULTICAST
Function Documentation
void NWK_SetAckControl (uint8_t control)
References nwkRxAckControl.
void nwkRxDecryptConf (NwkFrame_t * frame, bool status)
void nwkRxInit (void)
Initializes the Rx module.
References SYS_Timer_t::handler, SYS_Timer_t::interval, SYS_Timer_t::mode, NWK_DUPLICATE_REJECTION_TABLE_SIZE, NWK_OpenEndpoint(), NWK_RX_DUPLICATE_REJECTION_TIMER_INTERVAL, NWK_SERVICE_ENDPOINT_ID, nwkRxDuplicateRejectionTimerHandler(), nwkRxServiceDataInd(), and SYS_TIMER_INTERVAL_MODE.
Referenced by NWK_Init().
void nwkRxTaskHandler (void)
Rx Module task handler.
References NWK_RX_STATE_DECRYPT, NWK_RX_STATE_FINISH, NWK_RX_STATE_INDICATE, NWK_RX_STATE_RECEIVED, NWK_RX_STATE_ROUTE, nwkFrameFree(), nwkFrameNext(), nwkRxHandleIndication(), nwkRxHandleReceivedFrame(), and NwkFrame_t::state.
Referenced by NWK_TaskHandler().