C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/nwk/inc/nwkDataReq.h File Reference
NWK_DataReq() interface.
#include <stdint.h>
*
#include <stdbool.h>
*
#include `sysConfig.h`
*
#include `sysTypes.h`
*
Data Structures
struct NWK_DataReq_t
Typedefs
typedef struct NWK_DataReq_t NWK_DataReq_t
Enumerations
enum {
*
NWK_OPT_ACK_REQUEST = 1 << 0,
NWK_OPT_ENABLE_SECURITY = 1 << 1,
NWK_OPT_BROADCAST_PAN_ID = 1 << 2,
NWK_OPT_LINK_LOCAL = 1 << 3,
*
NWK_OPT_MULTICAST = 1 << 4
 }
Functions
void NWK_DataReq (NWK_DataReq_t *req)
Adds request req to the queue of outgoing requests.
void nwkDataReqInit (void)
Initializes the Data Request module.
void nwkDataReqTaskHandler (void)
Data Request module task handler.
Detailed Description
NWK_DataReq() interface. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
nwkDataReq.h 9267 2014-03-18 21:46:19Z ataradov
Typedef Documentation
typedef struct NWK_DataReq_t NWK_DataReq_t
Enumeration Type Documentation
anonymous enum
Enumerator:
NWK_OPT_ACK_REQUEST
NWK_OPT_ENABLE_SECURITY
NWK_OPT_BROADCAST_PAN_ID
NWK_OPT_LINK_LOCAL
NWK_OPT_MULTICAST
Function Documentation
void NWK_DataReq (NWK_DataReq_t * req)
Adds request req to the queue of outgoing requests.
Parameters
in req Pointer to the request parameters
References NWK_DataReq_t::frame, NwkIb_t::lock, NWK_DataReq_t::next, NWK_DATA_REQ_STATE_INITIAL, NWK_SUCCESS_STATUS, nwkDataReqQueue, nwkIb, NWK_DataReq_t::state, and NWK_DataReq_t::status.
void nwkDataReqInit (void)
Initializes the Data Request module.
Referenced by NWK_Init().
void nwkDataReqTaskHandler (void)
Data Request module task handler.
References NWK_DataReq_t::next, NWK_DATA_REQ_STATE_CONFIRM, NWK_DATA_REQ_STATE_INITIAL, NWK_DATA_REQ_STATE_WAIT_CONF, nwkDataReqConfirm(), and nwkDataReqSendFrame().
Referenced by NWK_TaskHandler().