C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/nwk/inc/nwk.h File Reference
Network layer public interface.
#include <stdint.h>
*
#include <stdbool.h>
*
#include `sysConfig.h`
*
#include `nwkRoute.h`
*
#include `nwkGroup.h`
*
#include `nwkSecurity.h`
*
#include `nwkDataReq.h`
*
Data Structures
struct NwkIb_t
Macros
#define NWK_MAX_PAYLOAD_SIZE (127 - 16/*NwkFrameHeader_t*/ - 2/*crc*/)
#define NWK_BROADCAST_PANID 0xffff
#define NWK_BROADCAST_ADDR 0xffff
#define NWK_ENDPOINTS_AMOUNT 16
Typedefs
typedef struct NwkIb_t NwkIb_t
Enumerations
enum NWK_Status_t {
*
NWK_SUCCESS_STATUS = 0x00,
NWK_ERROR_STATUS = 0x01,
NWK_OUT_OF_MEMORY_STATUS = 0x02,
NWK_NO_ACK_STATUS = 0x10,
*
NWK_NO_ROUTE_STATUS = 0x11,
NWK_PHY_CHANNEL_ACCESS_FAILURE_STATUS = 0x20,
NWK_PHY_NO_ACK_STATUS = 0x21
 }
Functions
void NWK_Init (void)
Initializes all network layer modules.
void NWK_SetAddr (uint16_t addr)
Sets network address of the node.
void NWK_SetPanId (uint16_t panId)
Sets network identifier (PAN) of the node.
void NWK_OpenEndpoint (uint8_t id, bool(*handler)(NWK_DataInd_t *ind))
Registers callback ind for the endpoint endpoint.
bool NWK_Busy (void)
Checks if network layer is ready for sleep.
void NWK_Lock (void)
Increases the lock counter and sets a busy state.
void NWK_Unlock (void)
Decreases the lock counter and sets a free state if counter reaches 0.
void NWK_SleepReq (void)
Puts network layer to a sleeping state.
void NWK_WakeupReq (void)
Puts network layer to an active state.
void NWK_TaskHandler (void)
Network layer task handler.
uint8_t NWK_LinearizeLqi (uint8_t lqi)
Calculates linearized value for the given value of the LQI.
Variables
NwkIb_t nwkIb
Detailed Description
Network layer public interface. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
nwk.h 9267 2014-03-18 21:46:19Z ataradov
Macro Definition Documentation
#define NWK_BROADCAST_ADDR 0xffff
Referenced by nwkRxHandleIndication(), nwkRxHandleReceivedFrame(), nwkRxIndicateFrame(), nwkTxBroadcastFrame(), and nwkTxFrame().
#define NWK_BROADCAST_PANID 0xffff
Referenced by nwkRxHandleIndication(), nwkRxHandleReceivedFrame(), nwkRxIndicateFrame(), and nwkTxFrame().
#define NWK_ENDPOINTS_AMOUNT 16
Referenced by NWK_Init().
#define NWK_MAX_PAYLOAD_SIZE (127 - 16/*NwkFrameHeader_t*/ - 2/*crc*/)
Typedef Documentation
typedef struct NwkIb_t NwkIb_t
Enumeration Type Documentation
enum NWK_Status_t
Enumerator:
NWK_SUCCESS_STATUS
NWK_ERROR_STATUS
NWK_OUT_OF_MEMORY_STATUS
NWK_NO_ACK_STATUS
NWK_NO_ROUTE_STATUS
NWK_PHY_CHANNEL_ACCESS_FAILURE_STATUS
NWK_PHY_NO_ACK_STATUS
Function Documentation
bool NWK_Busy (void)
Checks if network layer is ready for sleep.
Returns
true if network layer is ready for sleep or false otherwise
References NwkIb_t::lock.
void NWK_Init (void)
Initializes all network layer modules.
References NwkIb_t::addr, NwkIb_t::endpoint, NwkIb_t::lock, NwkIb_t::macSeqNum, NWK_ENDPOINTS_AMOUNT, nwkDataReqInit(), nwkFrameInit(), nwkRxInit(), NwkIb_t::nwkSeqNum, and nwkTxInit().
Referenced by SYS_Init().
uint8_t NWK_LinearizeLqi (uint8_t lqi)
Calculates linearized value for the given value of the LQI.
Parameters
in lqi LQI value as provided by the transceiver
Returns
linearized value directly proportional to the probability of delivery
void NWK_Lock (void)
Increases the lock counter and sets a busy state.
References NwkIb_t::lock.
void NWK_OpenEndpoint (uint8_t id, bool(*)(NWK_DataInd_t *ind) handler)
Registers callback ind for the endpoint endpoint.
Parameters
in id Endpoint index (1-15)
in handler Pointer to the callback function
References NwkIb_t::endpoint.
Referenced by nwkRxInit().
void NWK_SetAddr (uint16_t addr)
Sets network address of the node.
Parameters
in addr Adddress to set
References NwkIb_t::addr, and PHY_SetShortAddr().
void NWK_SetPanId (uint16_t panId)
Sets network identifier (PAN) of the node.
Parameters
in panId PAN ID to set
References NwkIb_t::panId, and PHY_SetPanId().
void NWK_SleepReq (void)
Puts network layer to a sleeping state.
References PHY_Sleep().
void NWK_TaskHandler (void)
Network layer task handler.
References nwkDataReqTaskHandler(), nwkRxTaskHandler(), and nwkTxTaskHandler().
Referenced by SYS_TaskHandler().
void NWK_Unlock (void)
Decreases the lock counter and sets a free state if counter reaches 0.
References NwkIb_t::lock.
void NWK_WakeupReq (void)
Puts network layer to an active state.
References PHY_Wakeup().
Variable Documentation
NwkIb_t nwkIb
Referenced by NWK_DataReq(), nwkDataReqConfirm(), nwkDataReqSendFrame(), nwkFrameAlloc(), nwkFrameCommandInit(), nwkFrameFree(), nwkRxHandleIndication(), nwkRxHandleReceivedFrame(), nwkRxIndicateFrame(), nwkRxRejectDuplicate(), nwkTxBroadcastFrame(), nwkTxFrame(), nwkTxTaskHandler(), and PHY_DataConf().