C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/phy/atmegarfr2/inc/phy.h File Reference
ATMEGAxxxRFR2 PHY interface.
#include <stdint.h>
*
#include <stdbool.h>
*
#include `sysConfig.h`
*
Data Structures
struct PHY_DataInd_t
Macros
#define PHY_RSSI_BASE_VAL (-90)
#define PHY_HAS_RANDOM_NUMBER_GENERATOR
#define PHY_HAS_AES_MODULE
Typedefs
typedef struct PHY_DataInd_t PHY_DataInd_t
Enumerations
enum { PHY_STATUS_SUCCESS = 0,
PHY_STATUS_CHANNEL_ACCESS_FAILURE = 1,
PHY_STATUS_NO_ACK = 2,
PHY_STATUS_ERROR = 3
 }
Functions
void PHY_Init (void)
void PHY_SetRxState (bool rx)
void PHY_SetChannel (uint8_t channel)
void PHY_SetBand (uint8_t band)
void PHY_SetPanId (uint16_t panId)
void PHY_SetShortAddr (uint16_t addr)
void PHY_SetTxPower (uint8_t txPower)
void PHY_Sleep (void)
void PHY_Wakeup (void)
void PHY_DataReq (uint8_t *data, uint8_t size)
void PHY_DataConf (uint8_t status)
void PHY_DataInd (PHY_DataInd_t *ind)
void PHY_TaskHandler (void)
Detailed Description
ATMEGAxxxRFR2 PHY interface. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
phy.h 9267 2014-03-18 21:46:19Z ataradov
Macro Definition Documentation
#define PHY_HAS_AES_MODULE
#define PHY_HAS_RANDOM_NUMBER_GENERATOR
#define PHY_RSSI_BASE_VAL (-90)
Typedef Documentation
typedef struct PHY_DataInd_t PHY_DataInd_t
Enumeration Type Documentation
anonymous enum
Enumerator:
PHY_STATUS_SUCCESS
PHY_STATUS_CHANNEL_ACCESS_FAILURE
PHY_STATUS_NO_ACK
PHY_STATUS_ERROR
Function Documentation
void PHY_DataConf (uint8_t status)
References NwkIb_t::lock, NWK_TX_STATE_SENT, nwkIb, nwkTxConvertPhyStatus(), NwkFrame_t::state, and NwkFrame_t::tx.
void PHY_DataInd (PHY_DataInd_t * ind)
References PHY_DataInd_t::data, NwkFrame_t::data, PHY_DataInd_t::lqi, NWK_RX_STATE_RECEIVED, nwkFrameAlloc(), PHY_DataInd_t::rssi, NwkFrame_t::rx, PHY_DataInd_t::size, NwkFrame_t::size, and NwkFrame_t::state.
void PHY_DataReq (uint8_t * data, uint8_t size)
Referenced by nwkTxTaskHandler().
void PHY_Init (void)
Referenced by SYS_Init().
void PHY_SetBand (uint8_t band)
void PHY_SetChannel (uint8_t channel)
void PHY_SetPanId (uint16_t panId)
Referenced by NWK_SetPanId().
void PHY_SetRxState (bool rx)
void PHY_SetShortAddr (uint16_t addr)
Referenced by NWK_SetAddr().
void PHY_SetTxPower (uint8_t txPower)
void PHY_Sleep (void)
Referenced by NWK_SleepReq().
void PHY_TaskHandler (void)
Referenced by SYS_TaskHandler().
void PHY_Wakeup (void)
Referenced by NWK_WakeupReq().