C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/scheduler/inc/scheduler.h File Reference
The resources that hold all events and manage useful events in-order within a linked list.
#include `scheduler/inc/event.h`
*
#include `scheduler/inc/handler.h`
*
#include `utilities/inc/llist.h`
*
#include `drivers/inc/int_timer.h`
*
Macros
#define DEBUG
#define MAX_EVENTS 16
Max number of available device within a scheduler.
#define MAX_SLEEP_INTERVAL 8000
The max sleep time(ms) with current timer support.
#define EV_NULL (struct event *) (LL_NULL)
Null pointer of a event.
Functions
void dump_timeoutq ()
API of scheduler
API of the Round-Robin Scheduler
int load_new_sensor (int timeout, int repeat, BaseSensor *device_ptr, int otherinfo)
Load a brand new device activity into the scheduler's timeoutQ.
void init_timeoutq ()
Init function of scheduler, which initialize all events and put them into freelist.
int get_next_interval ()
Return the the time (ms) of the next event.
void insert_timeoutq_event (struct event *event_pointer)
Insert a new event into the scheduler according to timeout order.
int handle_timeoutq_event ()
Handle the next event in timeoutQ: execute the event's handler function according to the device type, re-insert it according to the period, and set a timer of next event.
Variables
list anchors
Important, but ignore them; they are never used directly
llobject_t TQ
TimeoutQueue anchor.
llobject_t FL
FreeList anchor.
Event list/queue
The linked list resource, where each node is an event
struct event * timeoutq
TimeoutQueue, which holds the events in line.
struct event * freelist
FreeList, which holds the events ready to hold new device.
struct event queue [MAX_EVENTS]
Declaration of event resources, and all events are within this queue.
Detailed Description
The resources that hold all events and manage useful events in-order within a linked list. Created: 2016/4/14 23:05:30 Author: Anxin Bai
Macro Definition Documentation
#define DEBUG
#define EV_NULL (struct event *) (LL_NULL)
Null pointer of a event.
Referenced by device_handler(), get_next_interval(), handle_timeoutq_event(), insert_timeoutq_event(), load_new_sensor(), and sensor_handler().
#define MAX_EVENTS 16
Max number of available device within a scheduler.
Referenced by init_timeoutq().
#define MAX_SLEEP_INTERVAL 8000
The max sleep time(ms) with current timer support.
Referenced by get_next_interval().
Function Documentation
void dump_timeoutq ()
int get_next_interval ()
Return the the time (ms) of the next event.
References EV_NULL, LL_TOP, MAX_SLEEP_INTERVAL, event::timeout, and timeoutq.
Referenced by handle_timeoutq_event(), and main().
int handle_timeoutq_event ()
Handle the next event in timeoutQ: execute the event's handler function according to the device type, re-insert it according to the period, and set a timer of next event.
References event::borrow_timeout, EV_NULL, freelist, get_next_interval(), handle_timeoutq_event(), insert_timeoutq_event(), LL_POP, LL_PUSH, LL_TOP, event::repeat_interval, event::run, set_timer(), event::sp, event::timeout, and timeoutq.
Referenced by handle_timeoutq_event().
void init_timeoutq ()
Init function of scheduler, which initialize all events and put them into freelist.
References FL, freelist, LL_INIT, LL_PUSH, MAX_EVENTS, queue, timeoutq, and TQ.
Referenced by main().
void insert_timeoutq_event (struct event * event_pointer)
Insert a new event into the scheduler according to timeout order.
References EV_NULL, LL_APPEND, LL_EACH, LL_L_INSERT, event::timeout, and timeoutq.
Referenced by handle_timeoutq_event(), load_new_sensor(), and sensor_handler().
int load_new_sensor (int timeout, int repeat, BaseSensor * device_ptr, int otherinfo)
Load a brand new device activity into the scheduler's timeoutQ.
References event::borrow_timeout, event::cur_state, EV_NULL, freelist, event::info, insert_timeoutq_event(), LL_POP, Ready, event::repeat_interval, event::run, sensor_handler(), event::sp, and event::timeout.
Referenced by main().
Variable Documentation
llobject_t FL
FreeList anchor.
Referenced by init_timeoutq().
struct event* freelist
FreeList, which holds the events ready to hold new device.
Referenced by handle_timeoutq_event(), init_timeoutq(), and load_new_sensor().
struct event queue[MAX_EVENTS]
Declaration of event resources, and all events are within this queue.
Referenced by init_timeoutq().
struct event* timeoutq
TimeoutQueue, which holds the events in line.
Referenced by get_next_interval(), handle_timeoutq_event(), init_timeoutq(), insert_timeoutq_event(), and sensor_handler().
llobject_t TQ
TimeoutQueue anchor.
Referenced by init_timeoutq().