C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/scheduler/src/scheduler.c File Reference
Implementation of the resources that hold all events and manage useful events in-order within a linked list.
#include `scheduler//inc/scheduler.h`
*
Functions
void init_timeoutq ()
Init function of scheduler, which initialize all events and put them into freelist.
int load_new_sensor (int timeout, int repeat, BaseSensor *device_ptr, int otherinfo)
Load a brand new device activity into the scheduler's timeoutQ.
int get_next_interval ()
Return the the time (ms) of the next event.
int handle_timeoutq_event ()
Handle the next event in timeoutQ: execute the event's handler function according to the device type, re-insert it according to the period, and set a timer of next event.
void insert_timeoutq_event (struct event *ep)
Insert a new event into the scheduler according to timeout order.
Detailed Description
Implementation of the resources that hold all events and manage useful events in-order within a linked list. Created: 2016/4/14 23:05:53 Author: Anxin Bai
Function Documentation
int get_next_interval ()
Return the the time (ms) of the next event.
References EV_NULL, LL_TOP, MAX_SLEEP_INTERVAL, event::timeout, and timeoutq.
Referenced by handle_timeoutq_event(), and main().
int handle_timeoutq_event ()
Handle the next event in timeoutQ: execute the event's handler function according to the device type, re-insert it according to the period, and set a timer of next event.
References event::borrow_timeout, EV_NULL, freelist, get_next_interval(), handle_timeoutq_event(), insert_timeoutq_event(), LL_POP, LL_PUSH, LL_TOP, event::repeat_interval, event::run, set_timer(), event::sp, event::timeout, and timeoutq.
Referenced by handle_timeoutq_event().
void init_timeoutq ()
Init function of scheduler, which initialize all events and put them into freelist.
References FL, freelist, LL_INIT, LL_PUSH, MAX_EVENTS, queue, timeoutq, and TQ.
Referenced by main().
void insert_timeoutq_event (struct event * ep)
Insert a new event into the scheduler according to timeout order.
References EV_NULL, LL_APPEND, LL_EACH, LL_L_INSERT, event::timeout, and timeoutq.
Referenced by handle_timeoutq_event(), load_new_sensor(), and sensor_handler().
int load_new_sensor (int timeout, int repeat, BaseSensor * device_ptr, int otherinfo)
Load a brand new device activity into the scheduler's timeoutQ.
References event::borrow_timeout, event::cur_state, EV_NULL, freelist, event::info, insert_timeoutq_event(), LL_POP, Ready, event::repeat_interval, event::run, sensor_handler(), event::sp, and event::timeout.
Referenced by main().