C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/sys/inc/sys.h File Reference
#include `sysConfig.h`
*
#include `phy.h`
*
#include `nwk.h`
*
#include `hal.h`
*
Functions
void SYS_Init (void)
void SYS_TaskHandler (void)
Function Documentation
void SYS_Init (void)
References HAL_Init(), NWK_Init(), PHY_Init(), and SYS_TimerInit().
Referenced by main().
void SYS_TaskHandler (void)
References NWK_TaskHandler(), PHY_TaskHandler(), and SYS_TimerTaskHandler().