C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/sys/src/sysTimer.c File Reference
System timer implementation.
#include <stdlib.h>
*
#include `hal.h`
*
#include `halTimer.h`
*
#include `sysTimer.h`
*
Functions
static void placeTimer (SYS_Timer_t *timer)
void SYS_TimerInit (void)
void SYS_TimerStart (SYS_Timer_t *timer)
void SYS_TimerStop (SYS_Timer_t *timer)
bool SYS_TimerStarted (SYS_Timer_t *timer)
void SYS_TimerTaskHandler (void)
Variables
static SYS_Timer_t * timers
Detailed Description
System timer implementation. Copyright (C) 2012-2014, Atmel Corporation. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The name of Atmel may not be used to endorse or promote products derived from this software without specific prior written permission.
This software may only be redistributed and used in connection with an Atmel microcontroller product.
THIS SOFTWARE IS PROVIDED BY ATMEL `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Modification and other use of this code is subject to Atmel's Limited License Agreement (license.txt).
Id:
sysTimer.c 9267 2014-03-18 21:46:19Z ataradov
Function Documentation
static void placeTimer (SYS_Timer_t * timer) [static]
References SYS_Timer_t::interval, SYS_Timer_t::next, SYS_Timer_t::timeout, timers, and uint32_t.
Referenced by SYS_TimerStart(), and SYS_TimerTaskHandler().
void SYS_TimerInit (void)
Referenced by SYS_Init().
void SYS_TimerStart (SYS_Timer_t * timer)
References placeTimer(), and SYS_TimerStarted().
Referenced by nwkRxDuplicateRejectionTimerHandler(), nwkRxRejectDuplicate(), nwkTxAckWaitTimerHandler(), nwkTxDelayTimerHandler(), and nwkTxTaskHandler().
bool SYS_TimerStarted (SYS_Timer_t * timer)
References SYS_Timer_t::next.
Referenced by SYS_TimerStart().
void SYS_TimerStop (SYS_Timer_t * timer)
References SYS_Timer_t::next, and SYS_Timer_t::timeout.
void SYS_TimerTaskHandler (void)
References ATOMIC_SECTION_ENTER, ATOMIC_SECTION_LEAVE, HAL_TIMER_INTERVAL, halTimerIrqCount, SYS_Timer_t::handler, SYS_Timer_t::mode, SYS_Timer_t::next, placeTimer(), SYS_TIMER_PERIODIC_MODE, SYS_Timer_t::timeout, timers, and uint32_t.
Referenced by SYS_TaskHandler().
Variable Documentation
SYS_Timer_t* timers [static]
Referenced by placeTimer(), and SYS_TimerTaskHandler().