C:/Users/AB/Documents/GitHub/ATMEL-ATMOS/ATMOS/drivers/inc/usart0.h File Reference
USART0 in UART mode.
#include <stdio.h>
*
Macros
#define F_CPU 16000000UL
Functions
int USART0_putchar_printf (char var, FILE *stream)
Called when stdout is being printed to USART0 (this is set up at runtime)
void USART0_Init (unsigned long baud)
Initializes USART0 in asynchronous UART mode, 8 bit data, 1 stop bit.
void USART0_Transmit (unsigned char data)
Transmits a byte via USART0.
unsigned char USART_Receive (void)
Receives a byte via USART0.
void USART_Flush (void)
Flushes out the USART0 receive buffer.
Variables
static FILE USART0_stdout = FDEV_SETUP_STREAM(USART0_putchar_printf, NULL, _FDEV_SETUP_WRITE)
Detailed Description
USART0 in UART mode. Created: 2/7/2015 20:37:01 Author: Camden Miller York
Macro Definition Documentation
#define F_CPU 16000000UL
Referenced by HAL_TimerInit(), TWI_Init(), and USART0_Init().
Function Documentation
void USART0_Init (unsigned long baud)
Initializes USART0 in asynchronous UART mode, 8 bit data, 1 stop bit.
Parameters
in desired baud rate (configuration values computed using F_CPU)
References F_CPU, and USART0_stdout.
Referenced by APP_Init().
int USART0_putchar_printf (char var, FILE * stream)
Called when stdout is being printed to USART0 (this is set up at runtime)
Calls USART0_Transmit which contains busy loops, not production code
Parameters
in var byte to transmit
   in/out] *stream Pointer to a stdio.h FILE io stream
Returns
Status
References USART0_Transmit().
void USART0_Transmit (unsigned char data)
Transmits a byte via USART0.
Function contains busy loops for simplicity in debugging. Not production code.
Parameters
in data byte to be transmitted
Referenced by USART0_putchar_printf().
void USART_Flush (void)
Flushes out the USART0 receive buffer.
Function contains busy loops for simplicity in debugging. Not production code.
unsigned char USART_Receive (void)
Receives a byte via USART0.
Function contains busy loops for simplicity in debugging. Not production code.
Returns
the received byte
Variable Documentation
FILE USART0_stdout = FDEV_SETUP_STREAM(USART0_putchar_printf, NULL, _FDEV_SETUP_WRITE) [static]
Referenced by USART0_Init().